// Code generated by protoc-gen-go. DO NOT EDIT.
// source: item/item.proto

package proto_item

import (
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	common "github.com/v1990/protoc-gen-goku/examples/eshop/proto/out_go/common"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

type ItemInfo struct {
	ItemID               uint64   `protobuf:"varint,1,opt,name=itemID,proto3" json:"itemID,omitempty"`
	Name                 string   `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
	Price                string   `protobuf:"bytes,3,opt,name=price,proto3" json:"price,omitempty"`
	Intro                string   `protobuf:"bytes,4,opt,name=intro,proto3" json:"intro,omitempty"`
	CategoryID           uint64   `protobuf:"varint,5,opt,name=categoryID,proto3" json:"categoryID,omitempty"`
	Pictures             []string `protobuf:"bytes,6,rep,name=pictures,proto3" json:"pictures,omitempty"`
	Tags                 []uint64 `protobuf:"varint,7,rep,packed,name=tags,proto3" json:"tags,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *ItemInfo) Reset()         { *m = ItemInfo{} }
func (m *ItemInfo) String() string { return proto.CompactTextString(m) }
func (*ItemInfo) ProtoMessage()    {}
func (*ItemInfo) Descriptor() ([]byte, []int) {
	return fileDescriptor_317dd7afc15c77d3, []int{0}
}

func (m *ItemInfo) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ItemInfo.Unmarshal(m, b)
}
func (m *ItemInfo) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ItemInfo.Marshal(b, m, deterministic)
}
func (m *ItemInfo) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ItemInfo.Merge(m, src)
}
func (m *ItemInfo) XXX_Size() int {
	return xxx_messageInfo_ItemInfo.Size(m)
}
func (m *ItemInfo) XXX_DiscardUnknown() {
	xxx_messageInfo_ItemInfo.DiscardUnknown(m)
}

var xxx_messageInfo_ItemInfo proto.InternalMessageInfo

func (m *ItemInfo) GetItemID() uint64 {
	if m != nil {
		return m.ItemID
	}
	return 0
}

func (m *ItemInfo) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

func (m *ItemInfo) GetPrice() string {
	if m != nil {
		return m.Price
	}
	return ""
}

func (m *ItemInfo) GetIntro() string {
	if m != nil {
		return m.Intro
	}
	return ""
}

func (m *ItemInfo) GetCategoryID() uint64 {
	if m != nil {
		return m.CategoryID
	}
	return 0
}

func (m *ItemInfo) GetPictures() []string {
	if m != nil {
		return m.Pictures
	}
	return nil
}

func (m *ItemInfo) GetTags() []uint64 {
	if m != nil {
		return m.Tags
	}
	return nil
}

type ListItemReq struct {
	Head                 *common.ReqHead `protobuf:"bytes,1,opt,name=head,proto3" json:"head,omitempty"`
	CategoryID           uint64          `protobuf:"varint,2,opt,name=categoryID,proto3" json:"categoryID,omitempty"`
	Keyword              string          `protobuf:"bytes,3,opt,name=keyword,proto3" json:"keyword,omitempty"`
	XXX_NoUnkeyedLiteral struct{}        `json:"-"`
	XXX_unrecognized     []byte          `json:"-"`
	XXX_sizecache        int32           `json:"-"`
}

func (m *ListItemReq) Reset()         { *m = ListItemReq{} }
func (m *ListItemReq) String() string { return proto.CompactTextString(m) }
func (*ListItemReq) ProtoMessage()    {}
func (*ListItemReq) Descriptor() ([]byte, []int) {
	return fileDescriptor_317dd7afc15c77d3, []int{1}
}

func (m *ListItemReq) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ListItemReq.Unmarshal(m, b)
}
func (m *ListItemReq) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ListItemReq.Marshal(b, m, deterministic)
}
func (m *ListItemReq) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ListItemReq.Merge(m, src)
}
func (m *ListItemReq) XXX_Size() int {
	return xxx_messageInfo_ListItemReq.Size(m)
}
func (m *ListItemReq) XXX_DiscardUnknown() {
	xxx_messageInfo_ListItemReq.DiscardUnknown(m)
}

var xxx_messageInfo_ListItemReq proto.InternalMessageInfo

func (m *ListItemReq) GetHead() *common.ReqHead {
	if m != nil {
		return m.Head
	}
	return nil
}

func (m *ListItemReq) GetCategoryID() uint64 {
	if m != nil {
		return m.CategoryID
	}
	return 0
}

func (m *ListItemReq) GetKeyword() string {
	if m != nil {
		return m.Keyword
	}
	return ""
}

type ListItemResp struct {
	Head                 *common.ReqHead `protobuf:"bytes,1,opt,name=head,proto3" json:"head,omitempty"`
	Err                  *common.Error   `protobuf:"bytes,2,opt,name=err,proto3" json:"err,omitempty"`
	Items                []*ItemInfo     `protobuf:"bytes,3,rep,name=items,proto3" json:"items,omitempty"`
	XXX_NoUnkeyedLiteral struct{}        `json:"-"`
	XXX_unrecognized     []byte          `json:"-"`
	XXX_sizecache        int32           `json:"-"`
}

func (m *ListItemResp) Reset()         { *m = ListItemResp{} }
func (m *ListItemResp) String() string { return proto.CompactTextString(m) }
func (*ListItemResp) ProtoMessage()    {}
func (*ListItemResp) Descriptor() ([]byte, []int) {
	return fileDescriptor_317dd7afc15c77d3, []int{2}
}

func (m *ListItemResp) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ListItemResp.Unmarshal(m, b)
}
func (m *ListItemResp) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ListItemResp.Marshal(b, m, deterministic)
}
func (m *ListItemResp) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ListItemResp.Merge(m, src)
}
func (m *ListItemResp) XXX_Size() int {
	return xxx_messageInfo_ListItemResp.Size(m)
}
func (m *ListItemResp) XXX_DiscardUnknown() {
	xxx_messageInfo_ListItemResp.DiscardUnknown(m)
}

var xxx_messageInfo_ListItemResp proto.InternalMessageInfo

func (m *ListItemResp) GetHead() *common.ReqHead {
	if m != nil {
		return m.Head
	}
	return nil
}

func (m *ListItemResp) GetErr() *common.Error {
	if m != nil {
		return m.Err
	}
	return nil
}

func (m *ListItemResp) GetItems() []*ItemInfo {
	if m != nil {
		return m.Items
	}
	return nil
}

type ItemDetailReq struct {
	Head                 *common.ReqHead `protobuf:"bytes,1,opt,name=head,proto3" json:"head,omitempty"`
	ItemID               uint64          `protobuf:"varint,2,opt,name=itemID,proto3" json:"itemID,omitempty"`
	XXX_NoUnkeyedLiteral struct{}        `json:"-"`
	XXX_unrecognized     []byte          `json:"-"`
	XXX_sizecache        int32           `json:"-"`
}

func (m *ItemDetailReq) Reset()         { *m = ItemDetailReq{} }
func (m *ItemDetailReq) String() string { return proto.CompactTextString(m) }
func (*ItemDetailReq) ProtoMessage()    {}
func (*ItemDetailReq) Descriptor() ([]byte, []int) {
	return fileDescriptor_317dd7afc15c77d3, []int{3}
}

func (m *ItemDetailReq) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ItemDetailReq.Unmarshal(m, b)
}
func (m *ItemDetailReq) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ItemDetailReq.Marshal(b, m, deterministic)
}
func (m *ItemDetailReq) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ItemDetailReq.Merge(m, src)
}
func (m *ItemDetailReq) XXX_Size() int {
	return xxx_messageInfo_ItemDetailReq.Size(m)
}
func (m *ItemDetailReq) XXX_DiscardUnknown() {
	xxx_messageInfo_ItemDetailReq.DiscardUnknown(m)
}

var xxx_messageInfo_ItemDetailReq proto.InternalMessageInfo

func (m *ItemDetailReq) GetHead() *common.ReqHead {
	if m != nil {
		return m.Head
	}
	return nil
}

func (m *ItemDetailReq) GetItemID() uint64 {
	if m != nil {
		return m.ItemID
	}
	return 0
}

type ItemDetailCell struct {
	Key                  uint64   `protobuf:"varint,1,opt,name=key,proto3" json:"key,omitempty"`
	Value                string   `protobuf:"bytes,2,opt,name=value,proto3" json:"value,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *ItemDetailCell) Reset()         { *m = ItemDetailCell{} }
func (m *ItemDetailCell) String() string { return proto.CompactTextString(m) }
func (*ItemDetailCell) ProtoMessage()    {}
func (*ItemDetailCell) Descriptor() ([]byte, []int) {
	return fileDescriptor_317dd7afc15c77d3, []int{4}
}

func (m *ItemDetailCell) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ItemDetailCell.Unmarshal(m, b)
}
func (m *ItemDetailCell) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ItemDetailCell.Marshal(b, m, deterministic)
}
func (m *ItemDetailCell) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ItemDetailCell.Merge(m, src)
}
func (m *ItemDetailCell) XXX_Size() int {
	return xxx_messageInfo_ItemDetailCell.Size(m)
}
func (m *ItemDetailCell) XXX_DiscardUnknown() {
	xxx_messageInfo_ItemDetailCell.DiscardUnknown(m)
}

var xxx_messageInfo_ItemDetailCell proto.InternalMessageInfo

func (m *ItemDetailCell) GetKey() uint64 {
	if m != nil {
		return m.Key
	}
	return 0
}

func (m *ItemDetailCell) GetValue() string {
	if m != nil {
		return m.Value
	}
	return ""
}

type ItemDetailResp struct {
	Head                 *common.ReqHead   `protobuf:"bytes,1,opt,name=head,proto3" json:"head,omitempty"`
	Err                  *common.Error     `protobuf:"bytes,2,opt,name=err,proto3" json:"err,omitempty"`
	ItemID               uint64            `protobuf:"varint,3,opt,name=itemID,proto3" json:"itemID,omitempty"`
	Name                 string            `protobuf:"bytes,4,opt,name=name,proto3" json:"name,omitempty"`
	Price                string            `protobuf:"bytes,5,opt,name=price,proto3" json:"price,omitempty"`
	Intro                string            `protobuf:"bytes,6,opt,name=intro,proto3" json:"intro,omitempty"`
	CategoryID           uint64            `protobuf:"varint,7,opt,name=categoryID,proto3" json:"categoryID,omitempty"`
	Pictures             []string          `protobuf:"bytes,8,rep,name=pictures,proto3" json:"pictures,omitempty"`
	Tags                 []uint64          `protobuf:"varint,9,rep,packed,name=tags,proto3" json:"tags,omitempty"`
	Details              []*ItemDetailCell `protobuf:"bytes,10,rep,name=details,proto3" json:"details,omitempty"`
	XXX_NoUnkeyedLiteral struct{}          `json:"-"`
	XXX_unrecognized     []byte            `json:"-"`
	XXX_sizecache        int32             `json:"-"`
}

func (m *ItemDetailResp) Reset()         { *m = ItemDetailResp{} }
func (m *ItemDetailResp) String() string { return proto.CompactTextString(m) }
func (*ItemDetailResp) ProtoMessage()    {}
func (*ItemDetailResp) Descriptor() ([]byte, []int) {
	return fileDescriptor_317dd7afc15c77d3, []int{5}
}

func (m *ItemDetailResp) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ItemDetailResp.Unmarshal(m, b)
}
func (m *ItemDetailResp) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ItemDetailResp.Marshal(b, m, deterministic)
}
func (m *ItemDetailResp) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ItemDetailResp.Merge(m, src)
}
func (m *ItemDetailResp) XXX_Size() int {
	return xxx_messageInfo_ItemDetailResp.Size(m)
}
func (m *ItemDetailResp) XXX_DiscardUnknown() {
	xxx_messageInfo_ItemDetailResp.DiscardUnknown(m)
}

var xxx_messageInfo_ItemDetailResp proto.InternalMessageInfo

func (m *ItemDetailResp) GetHead() *common.ReqHead {
	if m != nil {
		return m.Head
	}
	return nil
}

func (m *ItemDetailResp) GetErr() *common.Error {
	if m != nil {
		return m.Err
	}
	return nil
}

func (m *ItemDetailResp) GetItemID() uint64 {
	if m != nil {
		return m.ItemID
	}
	return 0
}

func (m *ItemDetailResp) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

func (m *ItemDetailResp) GetPrice() string {
	if m != nil {
		return m.Price
	}
	return ""
}

func (m *ItemDetailResp) GetIntro() string {
	if m != nil {
		return m.Intro
	}
	return ""
}

func (m *ItemDetailResp) GetCategoryID() uint64 {
	if m != nil {
		return m.CategoryID
	}
	return 0
}

func (m *ItemDetailResp) GetPictures() []string {
	if m != nil {
		return m.Pictures
	}
	return nil
}

func (m *ItemDetailResp) GetTags() []uint64 {
	if m != nil {
		return m.Tags
	}
	return nil
}

func (m *ItemDetailResp) GetDetails() []*ItemDetailCell {
	if m != nil {
		return m.Details
	}
	return nil
}

func init() {
	proto.RegisterType((*ItemInfo)(nil), "item.ItemInfo")
	proto.RegisterType((*ListItemReq)(nil), "item.ListItemReq")
	proto.RegisterType((*ListItemResp)(nil), "item.ListItemResp")
	proto.RegisterType((*ItemDetailReq)(nil), "item.ItemDetailReq")
	proto.RegisterType((*ItemDetailCell)(nil), "item.ItemDetailCell")
	proto.RegisterType((*ItemDetailResp)(nil), "item.ItemDetailResp")
}

func init() { proto.RegisterFile("item/item.proto", fileDescriptor_317dd7afc15c77d3) }

var fileDescriptor_317dd7afc15c77d3 = []byte{
	// 489 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0xac, 0x54, 0x4f, 0x6f, 0xd3, 0x4e,
	0x10, 0xfd, 0x25, 0x76, 0x9c, 0x64, 0xf2, 0x6b, 0x0b, 0xdb, 0x08, 0xad, 0x72, 0x00, 0xcb, 0x70,
	0xf0, 0xa5, 0x31, 0x04, 0x21, 0x51, 0x71, 0x83, 0x20, 0x11, 0x29, 0xe2, 0xb0, 0x47, 0x2e, 0x95,
	0xeb, 0x0c, 0x8e, 0x15, 0xdb, 0xeb, 0xee, 0xae, 0x0b, 0xe1, 0x43, 0x71, 0xe0, 0x13, 0xa2, 0xdd,
	0x8d, 0x71, 0x94, 0xa6, 0xa8, 0x07, 0x2e, 0xf6, 0xcc, 0x9b, 0xd9, 0x9d, 0x3f, 0xef, 0xd9, 0x70,
	0x96, 0x29, 0x2c, 0x22, 0xfd, 0x98, 0x56, 0x82, 0x2b, 0x4e, 0x5c, 0x6d, 0x4f, 0xce, 0x13, 0x5e,
	0x14, 0xbc, 0x8c, 0xec, 0xcb, 0x86, 0x82, 0x5f, 0x1d, 0x18, 0x2c, 0x14, 0x16, 0x8b, 0xf2, 0x2b,
	0x27, 0x4f, 0xc0, 0xd3, 0x99, 0x8b, 0x39, 0xed, 0xf8, 0x9d, 0xd0, 0x65, 0x3b, 0x8f, 0x10, 0x70,
	0xcb, 0xb8, 0x40, 0xda, 0xf5, 0x3b, 0xe1, 0x90, 0x19, 0x9b, 0x8c, 0xa1, 0x57, 0x89, 0x2c, 0x41,
	0xea, 0x18, 0xd0, 0x3a, 0x1a, 0xcd, 0x4a, 0x25, 0x38, 0x75, 0x2d, 0x6a, 0x1c, 0xf2, 0x14, 0x20,
	0x89, 0x15, 0xa6, 0x5c, 0x6c, 0x17, 0x73, 0xda, 0x33, 0x77, 0xef, 0x21, 0x64, 0x02, 0x83, 0x2a,
	0x4b, 0x54, 0x2d, 0x50, 0x52, 0xcf, 0x77, 0xc2, 0x21, 0xfb, 0xe3, 0xeb, 0xda, 0x2a, 0x4e, 0x25,
	0xed, 0xfb, 0x4e, 0xe8, 0x32, 0x63, 0x07, 0x39, 0x8c, 0x96, 0x99, 0x54, 0xba, 0x6f, 0x86, 0x37,
	0xe4, 0x39, 0xb8, 0x6b, 0x8c, 0x57, 0xa6, 0xe9, 0xd1, 0xec, 0x6c, 0xba, 0x1b, 0x90, 0xe1, 0xcd,
	0x27, 0x8c, 0x57, 0xcc, 0x04, 0x0f, 0x7a, 0xe8, 0xde, 0xe9, 0x81, 0x42, 0x7f, 0x83, 0xdb, 0x6f,
	0x5c, 0xac, 0x76, 0x13, 0x35, 0x6e, 0xf0, 0x03, 0xfe, 0x6f, 0xab, 0xc9, 0xea, 0x61, 0xe5, 0x9e,
	0x81, 0x83, 0x42, 0x98, 0x3a, 0xa3, 0xd9, 0x49, 0x93, 0xf3, 0x51, 0x08, 0x2e, 0x98, 0x8e, 0x90,
	0x17, 0xd0, 0xd3, 0xdb, 0x95, 0xd4, 0xf1, 0x9d, 0x70, 0x34, 0x3b, 0x9d, 0x1a, 0xbe, 0x1a, 0x2a,
	0x98, 0x0d, 0x06, 0x4b, 0x38, 0xd1, 0xd0, 0x1c, 0x55, 0x9c, 0xe5, 0x0f, 0x9e, 0xb5, 0xe5, 0xb1,
	0xbb, 0xcf, 0x63, 0xf0, 0x16, 0x4e, 0xdb, 0xdb, 0x3e, 0x60, 0x9e, 0x93, 0x47, 0xe0, 0x6c, 0x70,
	0xbb, 0xa3, 0x5b, 0x9b, 0x9a, 0xc1, 0xdb, 0x38, 0xaf, 0x1b, 0xb2, 0xad, 0x13, 0xfc, 0xec, 0xee,
	0x1f, 0xfd, 0x87, 0x6b, 0x68, 0x5b, 0x75, 0x8e, 0x4a, 0xce, 0x3d, 0x26, 0xb9, 0xde, 0x51, 0xc9,
	0x79, 0xf7, 0x4b, 0xae, 0xff, 0x57, 0xc9, 0x0d, 0xee, 0x91, 0xdc, 0xb0, 0x95, 0x1c, 0x99, 0x42,
	0x7f, 0x65, 0x66, 0x97, 0x14, 0x0c, 0x61, 0xe3, 0x96, 0xb0, 0x76, 0x9f, 0xac, 0x49, 0x9a, 0x95,
	0xe0, 0xea, 0x10, 0x89, 0xc0, 0xd5, 0xe2, 0x21, 0x8f, 0x6d, 0xfa, 0x9e, 0x6c, 0x27, 0xe4, 0x10,
	0x92, 0x55, 0xf0, 0x1f, 0x79, 0x03, 0x9e, 0xbd, 0x8f, 0x9c, 0x1f, 0x56, 0xd0, 0x87, 0xc6, 0x77,
	0x41, 0x7d, 0xec, 0xfd, 0xe7, 0x2f, 0xcb, 0x34, 0x53, 0xeb, 0xfa, 0x5a, 0xef, 0x38, 0xba, 0x7d,
	0x75, 0x79, 0xf9, 0x32, 0x32, 0x5f, 0x78, 0x72, 0x91, 0x62, 0x79, 0x91, 0xf2, 0x4d, 0x1d, 0xe1,
	0xf7, 0xb8, 0xa8, 0x72, 0x94, 0x11, 0xca, 0x35, 0xaf, 0x6c, 0x38, 0xe2, 0xb5, 0xba, 0x4a, 0xb9,
	0xf9, 0x5b, 0xbc, 0x33, 0xc8, 0x95, 0x36, 0xaf, 0x3d, 0x63, 0xbf, 0xfe, 0x1d, 0x00, 0x00, 0xff,
	0xff, 0x61, 0xd8, 0xfe, 0xbe, 0x4c, 0x04, 0x00, 0x00,
}
