// Code generated by protoc-gen-go. DO NOT EDIT.
// source: common/common.proto

package proto_common

import (
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

// 客户端请求头
type ReqHead struct {
	// 客户端请求序列号
	Seq                  uint64   `protobuf:"varint,1,opt,name=seq,proto3" json:"seq,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *ReqHead) Reset()         { *m = ReqHead{} }
func (m *ReqHead) String() string { return proto.CompactTextString(m) }
func (*ReqHead) ProtoMessage()    {}
func (*ReqHead) Descriptor() ([]byte, []int) {
	return fileDescriptor_8f954d82c0b891f6, []int{0}
}

func (m *ReqHead) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ReqHead.Unmarshal(m, b)
}
func (m *ReqHead) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ReqHead.Marshal(b, m, deterministic)
}
func (m *ReqHead) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ReqHead.Merge(m, src)
}
func (m *ReqHead) XXX_Size() int {
	return xxx_messageInfo_ReqHead.Size(m)
}
func (m *ReqHead) XXX_DiscardUnknown() {
	xxx_messageInfo_ReqHead.DiscardUnknown(m)
}

var xxx_messageInfo_ReqHead proto.InternalMessageInfo

func (m *ReqHead) GetSeq() uint64 {
	if m != nil {
		return m.Seq
	}
	return 0
}

// 服务端响应头
type RespHead struct {
	// 客户端请求序列号
	Seq                  uint64   `protobuf:"varint,1,opt,name=seq,proto3" json:"seq,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *RespHead) Reset()         { *m = RespHead{} }
func (m *RespHead) String() string { return proto.CompactTextString(m) }
func (*RespHead) ProtoMessage()    {}
func (*RespHead) Descriptor() ([]byte, []int) {
	return fileDescriptor_8f954d82c0b891f6, []int{1}
}

func (m *RespHead) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_RespHead.Unmarshal(m, b)
}
func (m *RespHead) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_RespHead.Marshal(b, m, deterministic)
}
func (m *RespHead) XXX_Merge(src proto.Message) {
	xxx_messageInfo_RespHead.Merge(m, src)
}
func (m *RespHead) XXX_Size() int {
	return xxx_messageInfo_RespHead.Size(m)
}
func (m *RespHead) XXX_DiscardUnknown() {
	xxx_messageInfo_RespHead.DiscardUnknown(m)
}

var xxx_messageInfo_RespHead proto.InternalMessageInfo

func (m *RespHead) GetSeq() uint64 {
	if m != nil {
		return m.Seq
	}
	return 0
}

// 认证token
type AuthToken struct {
	AccessToken          string   `protobuf:"bytes,1,opt,name=accessToken,proto3" json:"accessToken,omitempty"`
	TokenType            string   `protobuf:"bytes,2,opt,name=tokenType,proto3" json:"tokenType,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *AuthToken) Reset()         { *m = AuthToken{} }
func (m *AuthToken) String() string { return proto.CompactTextString(m) }
func (*AuthToken) ProtoMessage()    {}
func (*AuthToken) Descriptor() ([]byte, []int) {
	return fileDescriptor_8f954d82c0b891f6, []int{2}
}

func (m *AuthToken) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_AuthToken.Unmarshal(m, b)
}
func (m *AuthToken) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_AuthToken.Marshal(b, m, deterministic)
}
func (m *AuthToken) XXX_Merge(src proto.Message) {
	xxx_messageInfo_AuthToken.Merge(m, src)
}
func (m *AuthToken) XXX_Size() int {
	return xxx_messageInfo_AuthToken.Size(m)
}
func (m *AuthToken) XXX_DiscardUnknown() {
	xxx_messageInfo_AuthToken.DiscardUnknown(m)
}

var xxx_messageInfo_AuthToken proto.InternalMessageInfo

func (m *AuthToken) GetAccessToken() string {
	if m != nil {
		return m.AccessToken
	}
	return ""
}

func (m *AuthToken) GetTokenType() string {
	if m != nil {
		return m.TokenType
	}
	return ""
}

// 公共错误信息
type Error struct {
	Code                 int32    `protobuf:"varint,1,opt,name=code,proto3" json:"code,omitempty"`
	Detail               string   `protobuf:"bytes,2,opt,name=detail,proto3" json:"detail,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Error) Reset()         { *m = Error{} }
func (m *Error) String() string { return proto.CompactTextString(m) }
func (*Error) ProtoMessage()    {}
func (*Error) Descriptor() ([]byte, []int) {
	return fileDescriptor_8f954d82c0b891f6, []int{3}
}

func (m *Error) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Error.Unmarshal(m, b)
}
func (m *Error) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Error.Marshal(b, m, deterministic)
}
func (m *Error) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Error.Merge(m, src)
}
func (m *Error) XXX_Size() int {
	return xxx_messageInfo_Error.Size(m)
}
func (m *Error) XXX_DiscardUnknown() {
	xxx_messageInfo_Error.DiscardUnknown(m)
}

var xxx_messageInfo_Error proto.InternalMessageInfo

func (m *Error) GetCode() int32 {
	if m != nil {
		return m.Code
	}
	return 0
}

func (m *Error) GetDetail() string {
	if m != nil {
		return m.Detail
	}
	return ""
}

func init() {
	proto.RegisterType((*ReqHead)(nil), "common.ReqHead")
	proto.RegisterType((*RespHead)(nil), "common.RespHead")
	proto.RegisterType((*AuthToken)(nil), "common.AuthToken")
	proto.RegisterType((*Error)(nil), "common.Error")
}

func init() { proto.RegisterFile("common/common.proto", fileDescriptor_8f954d82c0b891f6) }

var fileDescriptor_8f954d82c0b891f6 = []byte{
	// 232 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x74, 0x90, 0x3f, 0x4b, 0x03, 0x41,
	0x10, 0xc5, 0x89, 0x26, 0xa7, 0x37, 0x36, 0xb2, 0x82, 0x04, 0x4c, 0x11, 0xae, 0xb2, 0x49, 0x56,
	0x49, 0x15, 0xac, 0x14, 0x04, 0xc1, 0x46, 0x96, 0x54, 0x36, 0xe1, 0xb2, 0x37, 0xec, 0x85, 0x64,
	0x6f, 0x36, 0xfb, 0x47, 0xf4, 0xdb, 0x4b, 0x66, 0x0f, 0xb4, 0x49, 0x35, 0xef, 0xf7, 0xde, 0xcc,
	0xc0, 0x0c, 0xdc, 0x68, 0xb2, 0x96, 0x3a, 0x99, 0xcb, 0xdc, 0x79, 0x8a, 0x24, 0x8a, 0x4c, 0xd5,
	0x1d, 0x5c, 0x28, 0x3c, 0xbc, 0x61, 0xdd, 0x88, 0x6b, 0x38, 0x0f, 0x78, 0x18, 0x0f, 0xa6, 0x83,
	0xfb, 0xa1, 0x3a, 0xca, 0x6a, 0x02, 0x97, 0x0a, 0x83, 0x3b, 0x91, 0xbe, 0x43, 0xf9, 0x9c, 0x62,
	0xbb, 0xa2, 0x1d, 0x76, 0x62, 0x0a, 0x57, 0xb5, 0xd6, 0x18, 0x02, 0x23, 0xb7, 0x95, 0xea, 0xbf,
	0x25, 0x26, 0x50, 0xc6, 0xa3, 0x58, 0xfd, 0x38, 0x1c, 0x9f, 0x71, 0xfe, 0x67, 0x54, 0x0b, 0x18,
	0xbd, 0x7a, 0x4f, 0x5e, 0x08, 0x18, 0x6a, 0x6a, 0x90, 0x37, 0x8c, 0x14, 0x6b, 0x71, 0x0b, 0x45,
	0x83, 0xb1, 0xde, 0xee, 0xfb, 0xb9, 0x9e, 0x5e, 0xd4, 0xe7, 0x87, 0xd9, 0xc6, 0x36, 0x6d, 0xe6,
	0x9a, 0xac, 0xfc, 0x7a, 0x5c, 0x2e, 0x1f, 0x24, 0x9f, 0xa7, 0x67, 0x06, 0xbb, 0x99, 0xa1, 0x5d,
	0x92, 0xf8, 0x5d, 0x5b, 0xb7, 0xc7, 0x20, 0x31, 0xb4, 0xe4, 0x72, 0x2c, 0x29, 0xc5, 0xb5, 0xa1,
	0xfe, 0x23, 0x4f, 0xec, 0xad, 0x33, 0x6c, 0x0a, 0xa6, 0xc5, 0x6f, 0x00, 0x00, 0x00, 0xff, 0xff,
	0xc6, 0x3c, 0x87, 0xbc, 0x36, 0x01, 0x00, 0x00,
}
