// Code generated by protoc-gen-goku.
// source: order/order.proto

package order

import (
	"context"
	proto_order "github.com/v1990/protoc-gen-goku/examples/eshop/proto/out_go/order"
)

func (t *orderHandler) Create(ctx context.Context, in *proto_order.CreateOrderReq, out *proto_order.CreateOrderResp) error {
	// TODO 在这里实现你的代码
	return nil
}
