// Code generated by protoc-gen-goku.
// source: order/order.proto

package order

import (
	proto_order "github.com/v1990/protoc-gen-goku/examples/eshop/proto/out_go/order"
)

type orderHandler struct {
}

func NewOrderHandler() proto_order.OrderHandler {
	return &orderHandler{}
}
