// Code generated by protoc-gen-goku.
// source: item/item.proto

package item

import (
	"context"
	proto_item "github.com/v1990/protoc-gen-goku/examples/eshop/proto/out_go/item"
)

func (t *itemHandler) Detail(ctx context.Context, in *proto_item.ItemDetailReq, out *proto_item.ItemDetailResp) error {
	// TODO 在这里实现你的代码
	return nil
}
