// Code generated by protoc-gen-goku.
// source: item/item.proto

package item

import (
	proto_item "github.com/v1990/protoc-gen-goku/examples/eshop/proto/out_go/item"
)

type itemHandler struct {
}

func NewItemHandler() proto_item.ItemHandler {
	return &itemHandler{}
}
