// Code generated by protoc-gen-goku. DO NOT EDIT.
// source: google/protobuf/descriptor.proto

package descriptors

// implemented Nestable types
var NestableDescriptors = []Nestable{
	new(DescriptorProto),
	new(EnumDescriptorProto),
}

// implemented ProtoType types
var ProtoTypeDescriptors = []ProtoType{
	new(DescriptorProto),
	new(EnumDescriptorProto),
}
