// Code generated by protoc-gen-goku. DO NOT EDIT.
// source: google/protobuf/descriptor.proto

package descriptors

import (
	bytes "bytes"
	jsonpb "github.com/gogo/protobuf/jsonpb"
	descriptorpb "google.golang.org/protobuf/types/descriptorpb"
)

// Range of reserved tag numbers. Reserved tag numbers may not be used by
// fields or extension ranges in the same message. Reserved ranges may
// not overlap.
//   See: descriptorpb.DescriptorProto_ReservedRange
type DescriptorProto_ReservedRange struct {
	common

	pb *descriptorpb.DescriptorProto_ReservedRange
}

func newDescriptorProto_ReservedRange(desc *descriptorpb.DescriptorProto_ReservedRange) *DescriptorProto_ReservedRange {
	t := new(DescriptorProto_ReservedRange)
	t.pb = desc

	t.setDescriptor(t)

	return t
}

//
// Inclusive.
//   See descriptorpb.DescriptorProto_ReservedRange DescriptorProto_ReservedRange.Start
//   SourceCodeInfo.Location.Path: [4 2 3 1 2 0]
//   proto info: {"name":"start","number":1,"label":"LABEL_OPTIONAL","type":"TYPE_INT32","jsonName":"start"}
func (t *DescriptorProto_ReservedRange) GetStart() (ret int32) {
	if t.Empty() {
		return
	}

	return t.pb.GetStart()

}

func (t *DescriptorProto_ReservedRange) Start() int32 {
	return t.GetStart()
}

//
// Exclusive.
//   See descriptorpb.DescriptorProto_ReservedRange DescriptorProto_ReservedRange.End
//   SourceCodeInfo.Location.Path: [4 2 3 1 2 1]
//   proto info: {"name":"end","number":2,"label":"LABEL_OPTIONAL","type":"TYPE_INT32","jsonName":"end"}
func (t *DescriptorProto_ReservedRange) GetEnd() (ret int32) {
	if t.Empty() {
		return
	}

	return t.pb.GetEnd()

}

func (t *DescriptorProto_ReservedRange) End() int32 {
	return t.GetEnd()
}

func (t *DescriptorProto_ReservedRange) PbDescriptor() *descriptorpb.DescriptorProto_ReservedRange {
	if t == nil || t.pb == nil {
		return nil
	}
	return t.pb
}

func (t *DescriptorProto_ReservedRange) DescriptorProto_ReservedRange() *descriptorpb.DescriptorProto_ReservedRange {
	return t.PbDescriptor()
}

func (t *DescriptorProto_ReservedRange) MarshalJSON() (b []byte, err error) {
	if t.Empty() {
		return
	}
	buf := bytes.NewBuffer(nil)
	err = (&jsonpb.Marshaler{}).Marshal(buf, t.pb)
	return buf.Bytes(), err
}

// implement DescriptorCommon.Empty()
func (t *DescriptorProto_ReservedRange) Empty() bool {
	return t == nil || t.pb == nil
}

// implement DescriptorCommon.Index()
func (t *DescriptorProto_ReservedRange) Index() int {
	if t.Empty() {
		return -1
	}

	return t.getIndex()
}

// implement DescriptorCommon.File()
func (t *DescriptorProto_ReservedRange) File() *FileDescriptorProto {
	if t.Empty() {
		return nil
	}

	return t.getFile()
}

// implement DescriptorCommon.Parent()
func (t *DescriptorProto_ReservedRange) Parent() DescriptorCommon {
	if t.Empty() {
		return nil
	}

	return t.getParent()
}

// implement DescriptorCommon.LocationPath()
func (t *DescriptorProto_ReservedRange) LocationPath() LocationPath {
	if t.Empty() {
		return nil
	}

	return t.getLocationPath()
}
