// Code generated by protoc-gen-goku. DO NOT EDIT.
// source: google/protobuf/descriptor.proto

package descriptors

import (
	bytes "bytes"
	jsonpb "github.com/gogo/protobuf/jsonpb"
	descriptorpb "google.golang.org/protobuf/types/descriptorpb"
)

// Describes a message type.
//   See: descriptorpb.DescriptorProto
type DescriptorProto struct {
	common

	pb *descriptorpb.DescriptorProto

	field []*FieldDescriptorProto

	extension []*FieldDescriptorProto

	nested_type []*DescriptorProto

	enum_type []*EnumDescriptorProto

	extension_range []*DescriptorProto_ExtensionRange

	oneof_decl []*OneofDescriptorProto

	options *MessageOptions

	reserved_range []*DescriptorProto_ReservedRange
}

func newDescriptorProto(desc *descriptorpb.DescriptorProto) *DescriptorProto {
	t := new(DescriptorProto)
	t.pb = desc

	t.setDescriptor(t)

	return t
}

//   See descriptorpb.DescriptorProto DescriptorProto.Name
//   SourceCodeInfo.Location.Path: [4 2 2 0]
//   proto info: {"name":"name","number":1,"label":"LABEL_OPTIONAL","type":"TYPE_STRING","jsonName":"name"}
func (t *DescriptorProto) GetName() (ret string) {
	if t.Empty() {
		return
	}

	return t.pb.GetName()

}

func (t *DescriptorProto) Name() string {
	return t.GetName()
}

//   See descriptorpb.DescriptorProto DescriptorProto.Field
//   SourceCodeInfo.Location.Path: [4 2 2 1]
//   proto info: {"name":"field","number":2,"label":"LABEL_REPEATED","type":"TYPE_MESSAGE","typeName":".google.protobuf.FieldDescriptorProto","jsonName":"field"}
func (t *DescriptorProto) GetField() (ret []*FieldDescriptorProto) {
	if t.Empty() {
		return
	}

	if t.field != nil {
		return t.field
	}

	t.field = make([]*FieldDescriptorProto, len(t.pb.GetField()))

	for i, item := range t.pb.GetField() {
		elem := newFieldDescriptorProto(item)
		elem.setParent(t)
		elem.setIndex(i)
		t.field[i] = elem
	}

	return t.field

}

func (t *DescriptorProto) Field() []*FieldDescriptorProto {
	return t.GetField()
}

//   See descriptorpb.DescriptorProto DescriptorProto.Extension
//   SourceCodeInfo.Location.Path: [4 2 2 2]
//   proto info: {"name":"extension","number":6,"label":"LABEL_REPEATED","type":"TYPE_MESSAGE","typeName":".google.protobuf.FieldDescriptorProto","jsonName":"extension"}
func (t *DescriptorProto) GetExtension() (ret []*FieldDescriptorProto) {
	if t.Empty() {
		return
	}

	if t.extension != nil {
		return t.extension
	}

	t.extension = make([]*FieldDescriptorProto, len(t.pb.GetExtension()))

	for i, item := range t.pb.GetExtension() {
		elem := newFieldDescriptorProto(item)
		elem.setParent(t)
		elem.setIndex(i)
		t.extension[i] = elem
	}

	return t.extension

}

func (t *DescriptorProto) Extension() []*FieldDescriptorProto {
	return t.GetExtension()
}

//   See descriptorpb.DescriptorProto DescriptorProto.NestedType
//   SourceCodeInfo.Location.Path: [4 2 2 3]
//   proto info: {"name":"nested_type","number":3,"label":"LABEL_REPEATED","type":"TYPE_MESSAGE","typeName":".google.protobuf.DescriptorProto","jsonName":"nestedType"}
func (t *DescriptorProto) GetNestedType() (ret []*DescriptorProto) {
	if t.Empty() {
		return
	}

	if t.nested_type != nil {
		return t.nested_type
	}

	t.nested_type = make([]*DescriptorProto, len(t.pb.GetNestedType()))

	for i, item := range t.pb.GetNestedType() {
		elem := newDescriptorProto(item)
		elem.setParent(t)
		elem.setIndex(i)
		t.nested_type[i] = elem
	}

	return t.nested_type

}

func (t *DescriptorProto) NestedType() []*DescriptorProto {
	return t.GetNestedType()
}

//   See descriptorpb.DescriptorProto DescriptorProto.EnumType
//   SourceCodeInfo.Location.Path: [4 2 2 4]
//   proto info: {"name":"enum_type","number":4,"label":"LABEL_REPEATED","type":"TYPE_MESSAGE","typeName":".google.protobuf.EnumDescriptorProto","jsonName":"enumType"}
func (t *DescriptorProto) GetEnumType() (ret []*EnumDescriptorProto) {
	if t.Empty() {
		return
	}

	if t.enum_type != nil {
		return t.enum_type
	}

	t.enum_type = make([]*EnumDescriptorProto, len(t.pb.GetEnumType()))

	for i, item := range t.pb.GetEnumType() {
		elem := newEnumDescriptorProto(item)
		elem.setParent(t)
		elem.setIndex(i)
		t.enum_type[i] = elem
	}

	return t.enum_type

}

func (t *DescriptorProto) EnumType() []*EnumDescriptorProto {
	return t.GetEnumType()
}

//   See descriptorpb.DescriptorProto DescriptorProto.ExtensionRange
//   SourceCodeInfo.Location.Path: [4 2 2 5]
//   proto info: {"name":"extension_range","number":5,"label":"LABEL_REPEATED","type":"TYPE_MESSAGE","typeName":".google.protobuf.DescriptorProto.ExtensionRange","jsonName":"extensionRange"}
func (t *DescriptorProto) GetExtensionRange() (ret []*DescriptorProto_ExtensionRange) {
	if t.Empty() {
		return
	}

	if t.extension_range != nil {
		return t.extension_range
	}

	t.extension_range = make([]*DescriptorProto_ExtensionRange, len(t.pb.GetExtensionRange()))

	for i, item := range t.pb.GetExtensionRange() {
		elem := newDescriptorProto_ExtensionRange(item)
		elem.setParent(t)
		elem.setIndex(i)
		t.extension_range[i] = elem
	}

	return t.extension_range

}

func (t *DescriptorProto) ExtensionRange() []*DescriptorProto_ExtensionRange {
	return t.GetExtensionRange()
}

//   See descriptorpb.DescriptorProto DescriptorProto.OneofDecl
//   SourceCodeInfo.Location.Path: [4 2 2 6]
//   proto info: {"name":"oneof_decl","number":8,"label":"LABEL_REPEATED","type":"TYPE_MESSAGE","typeName":".google.protobuf.OneofDescriptorProto","jsonName":"oneofDecl"}
func (t *DescriptorProto) GetOneofDecl() (ret []*OneofDescriptorProto) {
	if t.Empty() {
		return
	}

	if t.oneof_decl != nil {
		return t.oneof_decl
	}

	t.oneof_decl = make([]*OneofDescriptorProto, len(t.pb.GetOneofDecl()))

	for i, item := range t.pb.GetOneofDecl() {
		elem := newOneofDescriptorProto(item)
		elem.setParent(t)
		elem.setIndex(i)
		t.oneof_decl[i] = elem
	}

	return t.oneof_decl

}

func (t *DescriptorProto) OneofDecl() []*OneofDescriptorProto {
	return t.GetOneofDecl()
}

//   See descriptorpb.DescriptorProto DescriptorProto.Options
//   SourceCodeInfo.Location.Path: [4 2 2 7]
//   proto info: {"name":"options","number":7,"label":"LABEL_OPTIONAL","type":"TYPE_MESSAGE","typeName":".google.protobuf.MessageOptions","jsonName":"options"}
func (t *DescriptorProto) GetOptions() (ret *MessageOptions) {
	if t.Empty() {
		return
	}

	if t.options != nil {
		return t.options
	}

	t.options = newMessageOptions(t.pb.GetOptions())
	t.options.setParent(t)

	return t.options

}

func (t *DescriptorProto) Options() *MessageOptions {
	return t.GetOptions()
}

//   See descriptorpb.DescriptorProto DescriptorProto.ReservedRange
//   SourceCodeInfo.Location.Path: [4 2 2 8]
//   proto info: {"name":"reserved_range","number":9,"label":"LABEL_REPEATED","type":"TYPE_MESSAGE","typeName":".google.protobuf.DescriptorProto.ReservedRange","jsonName":"reservedRange"}
func (t *DescriptorProto) GetReservedRange() (ret []*DescriptorProto_ReservedRange) {
	if t.Empty() {
		return
	}

	if t.reserved_range != nil {
		return t.reserved_range
	}

	t.reserved_range = make([]*DescriptorProto_ReservedRange, len(t.pb.GetReservedRange()))

	for i, item := range t.pb.GetReservedRange() {
		elem := newDescriptorProto_ReservedRange(item)
		elem.setParent(t)
		elem.setIndex(i)
		t.reserved_range[i] = elem
	}

	return t.reserved_range

}

func (t *DescriptorProto) ReservedRange() []*DescriptorProto_ReservedRange {
	return t.GetReservedRange()
}

// Reserved field names, which may not be used by fields in the same message.
// A given name may only be reserved once.
//   See descriptorpb.DescriptorProto DescriptorProto.ReservedName
//   SourceCodeInfo.Location.Path: [4 2 2 9]
//   proto info: {"name":"reserved_name","number":10,"label":"LABEL_REPEATED","type":"TYPE_STRING","jsonName":"reservedName"}
func (t *DescriptorProto) GetReservedName() (ret []string) {
	if t.Empty() {
		return
	}

	return t.pb.GetReservedName()

}

func (t *DescriptorProto) ReservedName() []string {
	return t.GetReservedName()
}

func (t *DescriptorProto) PbDescriptor() *descriptorpb.DescriptorProto {
	if t == nil || t.pb == nil {
		return nil
	}
	return t.pb
}

func (t *DescriptorProto) DescriptorProto() *descriptorpb.DescriptorProto {
	return t.PbDescriptor()
}

func (t *DescriptorProto) MarshalJSON() (b []byte, err error) {
	if t.Empty() {
		return
	}
	buf := bytes.NewBuffer(nil)
	err = (&jsonpb.Marshaler{}).Marshal(buf, t.pb)
	return buf.Bytes(), err
}

// implement DescriptorCommon.Empty()
func (t *DescriptorProto) Empty() bool {
	return t == nil || t.pb == nil
}

// implement DescriptorCommon.Index()
func (t *DescriptorProto) Index() int {
	if t.Empty() {
		return -1
	}

	return t.getIndex()
}

// implement DescriptorCommon.File()
func (t *DescriptorProto) File() *FileDescriptorProto {
	if t.Empty() {
		return nil
	}

	return t.getFile()
}

// implement DescriptorCommon.Parent()
func (t *DescriptorProto) Parent() DescriptorCommon {
	if t.Empty() {
		return nil
	}

	return t.getParent()
}

// implement DescriptorCommon.LocationPath()
func (t *DescriptorProto) LocationPath() LocationPath {
	if t.Empty() {
		return nil
	}

	return t.getLocationPath()
}

// implement Nestable.IsNested()
func (t *DescriptorProto) IsNested() bool {
	if t.Empty() {
		return false
	}
	return t.isNested()
}

// implement Nestable.ParentMessage()
func (t *DescriptorProto) ParentMessage() *DescriptorProto {
	if t.Empty() {
		return nil
	}
	return t.parentMessage()
}
