// Code generated by protoc-gen-goku. DO NOT EDIT.
// source: google/protobuf/descriptor.proto

package descriptors

import (
	bytes "bytes"
	jsonpb "github.com/gogo/protobuf/jsonpb"
	descriptorpb "google.golang.org/protobuf/types/descriptorpb"
)

//   See: descriptorpb.DescriptorProto_ExtensionRange
type DescriptorProto_ExtensionRange struct {
	common

	pb *descriptorpb.DescriptorProto_ExtensionRange

	options *ExtensionRangeOptions
}

func newDescriptorProto_ExtensionRange(desc *descriptorpb.DescriptorProto_ExtensionRange) *DescriptorProto_ExtensionRange {
	t := new(DescriptorProto_ExtensionRange)
	t.pb = desc

	t.setDescriptor(t)

	return t
}

//
// Inclusive.
//   See descriptorpb.DescriptorProto_ExtensionRange DescriptorProto_ExtensionRange.Start
//   SourceCodeInfo.Location.Path: [4 2 3 0 2 0]
//   proto info: {"name":"start","number":1,"label":"LABEL_OPTIONAL","type":"TYPE_INT32","jsonName":"start"}
func (t *DescriptorProto_ExtensionRange) GetStart() (ret int32) {
	if t.Empty() {
		return
	}

	return t.pb.GetStart()

}

func (t *DescriptorProto_ExtensionRange) Start() int32 {
	return t.GetStart()
}

//
// Exclusive.
//   See descriptorpb.DescriptorProto_ExtensionRange DescriptorProto_ExtensionRange.End
//   SourceCodeInfo.Location.Path: [4 2 3 0 2 1]
//   proto info: {"name":"end","number":2,"label":"LABEL_OPTIONAL","type":"TYPE_INT32","jsonName":"end"}
func (t *DescriptorProto_ExtensionRange) GetEnd() (ret int32) {
	if t.Empty() {
		return
	}

	return t.pb.GetEnd()

}

func (t *DescriptorProto_ExtensionRange) End() int32 {
	return t.GetEnd()
}

//   See descriptorpb.DescriptorProto_ExtensionRange DescriptorProto_ExtensionRange.Options
//   SourceCodeInfo.Location.Path: [4 2 3 0 2 2]
//   proto info: {"name":"options","number":3,"label":"LABEL_OPTIONAL","type":"TYPE_MESSAGE","typeName":".google.protobuf.ExtensionRangeOptions","jsonName":"options"}
func (t *DescriptorProto_ExtensionRange) GetOptions() (ret *ExtensionRangeOptions) {
	if t.Empty() {
		return
	}

	if t.options != nil {
		return t.options
	}

	t.options = newExtensionRangeOptions(t.pb.GetOptions())
	t.options.setParent(t)

	return t.options

}

func (t *DescriptorProto_ExtensionRange) Options() *ExtensionRangeOptions {
	return t.GetOptions()
}

func (t *DescriptorProto_ExtensionRange) PbDescriptor() *descriptorpb.DescriptorProto_ExtensionRange {
	if t == nil || t.pb == nil {
		return nil
	}
	return t.pb
}

func (t *DescriptorProto_ExtensionRange) DescriptorProto_ExtensionRange() *descriptorpb.DescriptorProto_ExtensionRange {
	return t.PbDescriptor()
}

func (t *DescriptorProto_ExtensionRange) MarshalJSON() (b []byte, err error) {
	if t.Empty() {
		return
	}
	buf := bytes.NewBuffer(nil)
	err = (&jsonpb.Marshaler{}).Marshal(buf, t.pb)
	return buf.Bytes(), err
}

// implement DescriptorCommon.Empty()
func (t *DescriptorProto_ExtensionRange) Empty() bool {
	return t == nil || t.pb == nil
}

// implement DescriptorCommon.Index()
func (t *DescriptorProto_ExtensionRange) Index() int {
	if t.Empty() {
		return -1
	}

	return t.getIndex()
}

// implement DescriptorCommon.File()
func (t *DescriptorProto_ExtensionRange) File() *FileDescriptorProto {
	if t.Empty() {
		return nil
	}

	return t.getFile()
}

// implement DescriptorCommon.Parent()
func (t *DescriptorProto_ExtensionRange) Parent() DescriptorCommon {
	if t.Empty() {
		return nil
	}

	return t.getParent()
}

// implement DescriptorCommon.LocationPath()
func (t *DescriptorProto_ExtensionRange) LocationPath() LocationPath {
	if t.Empty() {
		return nil
	}

	return t.getLocationPath()
}
