// Code generated by protoc-gen-goku. DO NOT EDIT.
// source: google/protobuf/descriptor.proto

package descriptors

import (
	"google.golang.org/protobuf/types/descriptorpb"
)

// Describes a value within an enum.
//   See: descriptorpb.EnumValueDescriptorProto
type EnumValueDescriptorProto struct {
	common

	pb *descriptorpb.EnumValueDescriptorProto

	options *EnumValueOptions
}

func newEnumValueDescriptorProto(desc *descriptorpb.EnumValueDescriptorProto) *EnumValueDescriptorProto {
	t := new(EnumValueDescriptorProto)
	t.pb = desc

	t.setDescriptor(t)

	return t
}

//   See descriptorpb.EnumValueDescriptorProto EnumValueDescriptorProto.Name
//   SourceCodeInfo.Location.Path: [4 7 2 0]
//   proto info: {}
func (t *EnumValueDescriptorProto) GetName() (ret string) {
	if t.Empty() {
		return
	}

	return t.pb.GetName()

}

func (t *EnumValueDescriptorProto) Name() string {
	return t.GetName()
}

//   See descriptorpb.EnumValueDescriptorProto EnumValueDescriptorProto.Number
//   SourceCodeInfo.Location.Path: [4 7 2 1]
//   proto info: {}
func (t *EnumValueDescriptorProto) GetNumber() (ret int32) {
	if t.Empty() {
		return
	}

	return t.pb.GetNumber()

}

func (t *EnumValueDescriptorProto) Number() int32 {
	return t.GetNumber()
}

//   See descriptorpb.EnumValueDescriptorProto EnumValueDescriptorProto.Options
//   SourceCodeInfo.Location.Path: [4 7 2 2]
//   proto info: {}
func (t *EnumValueDescriptorProto) GetOptions() (ret *EnumValueOptions) {
	if t.Empty() {
		return
	}

	if t.options != nil {
		return t.options
	}

	t.options = newEnumValueOptions(t.pb.GetOptions())
	t.options.setParent(t)

	return t.options

}

func (t *EnumValueDescriptorProto) Options() *EnumValueOptions {
	return t.GetOptions()
}

func (t *EnumValueDescriptorProto) PbDescriptor() *descriptorpb.EnumValueDescriptorProto {
	if t == nil || t.pb == nil {
		return nil
	}
	return t.pb
}

func (t *EnumValueDescriptorProto) EnumValueDescriptorProto() *descriptorpb.EnumValueDescriptorProto {
	return t.PbDescriptor()
}

/*
func (t *EnumValueDescriptorProto) MarshalJSON() (b []byte,err error) {
    if t.Empty() {
        return
    }
    buf := bytes.NewBuffer(nil)
    err = (&jsonpb.Marshaler{}).Marshal(buf, t.pb)
    return buf.Bytes(), err
}
*/

// ExportFields returns can export fields
func (t *EnumValueDescriptorProto) ExportFields() map[string]interface{} {
	return map[string]interface{}{
		"Name":    t.Name(),
		"Number":  t.Number(),
		"Options": t.Options(),
	}
}

// implement DescriptorCommon.Empty()
func (t *EnumValueDescriptorProto) Empty() bool {
	return t == nil || t.pb == nil
}

// implement DescriptorCommon.Index()
func (t *EnumValueDescriptorProto) Index() int {
	if t.Empty() {
		return -1
	}

	return t.getIndex()
}

// implement DescriptorCommon.File()
func (t *EnumValueDescriptorProto) File() *FileDescriptorProto {
	if t.Empty() {
		return nil
	}

	return t.getFile()
}

// implement DescriptorCommon.Parent()
func (t *EnumValueDescriptorProto) Parent() DescriptorCommon {
	if t.Empty() {
		return nil
	}

	return t.getParent()
}

// implement DescriptorCommon.LocationPath()
func (t *EnumValueDescriptorProto) LocationPath() LocationPath {
	if t.Empty() {
		return nil
	}

	return t.getLocationPath()
}

func (t *EnumValueDescriptorProto) Comments() *SourceCodeInfo_Location {
	if t.Empty() {
		return nil
	}
	return t.getComments()
}
