// Code generated by protoc-gen-goku. DO NOT EDIT.
// source: google/protobuf/descriptor.proto

package descriptors

import (
	bytes "bytes"
	jsonpb "github.com/gogo/protobuf/jsonpb"
	descriptorpb "google.golang.org/protobuf/types/descriptorpb"
)

//   See: descriptorpb.EnumValueOptions
type EnumValueOptions struct {
	common

	pb *descriptorpb.EnumValueOptions

	uninterpreted_option []*UninterpretedOption
}

func newEnumValueOptions(desc *descriptorpb.EnumValueOptions) *EnumValueOptions {
	t := new(EnumValueOptions)
	t.pb = desc

	t.setDescriptor(t)

	return t
}

// Is this enum value deprecated?
// Depending on the target platform, this can emit Deprecated annotations
// for the enum value, or it will be completely ignored; in the very least,
// this is a formalization for deprecating enum values.
//   See descriptorpb.EnumValueOptions EnumValueOptions.Deprecated
//   SourceCodeInfo.Location.Path: [4 15 2 0]
//   proto info: {"name":"deprecated","number":1,"label":"LABEL_OPTIONAL","type":"TYPE_BOOL","defaultValue":"false","jsonName":"deprecated"}
func (t *EnumValueOptions) GetDeprecated() (ret bool) {
	if t.Empty() {
		return
	}

	return t.pb.GetDeprecated()

}

func (t *EnumValueOptions) Deprecated() bool {
	return t.GetDeprecated()
}

// The parser stores options it doesn't recognize here. See above.
//   See descriptorpb.EnumValueOptions EnumValueOptions.UninterpretedOption
//   SourceCodeInfo.Location.Path: [4 15 2 1]
//   proto info: {"name":"uninterpreted_option","number":999,"label":"LABEL_REPEATED","type":"TYPE_MESSAGE","typeName":".google.protobuf.UninterpretedOption","jsonName":"uninterpretedOption"}
func (t *EnumValueOptions) GetUninterpretedOption() (ret []*UninterpretedOption) {
	if t.Empty() {
		return
	}

	if t.uninterpreted_option != nil {
		return t.uninterpreted_option
	}

	t.uninterpreted_option = make([]*UninterpretedOption, len(t.pb.GetUninterpretedOption()))

	for i, item := range t.pb.GetUninterpretedOption() {
		elem := newUninterpretedOption(item)
		elem.setParent(t)
		elem.setIndex(i)
		t.uninterpreted_option[i] = elem
	}

	return t.uninterpreted_option

}

func (t *EnumValueOptions) UninterpretedOption() []*UninterpretedOption {
	return t.GetUninterpretedOption()
}

func (t *EnumValueOptions) PbDescriptor() *descriptorpb.EnumValueOptions {
	if t == nil || t.pb == nil {
		return nil
	}
	return t.pb
}

func (t *EnumValueOptions) EnumValueOptions() *descriptorpb.EnumValueOptions {
	return t.PbDescriptor()
}

func (t *EnumValueOptions) MarshalJSON() (b []byte, err error) {
	if t.Empty() {
		return
	}
	buf := bytes.NewBuffer(nil)
	err = (&jsonpb.Marshaler{}).Marshal(buf, t.pb)
	return buf.Bytes(), err
}

// implement DescriptorCommon.Empty()
func (t *EnumValueOptions) Empty() bool {
	return t == nil || t.pb == nil
}

// implement DescriptorCommon.Index()
func (t *EnumValueOptions) Index() int {
	if t.Empty() {
		return -1
	}

	return t.getIndex()
}

// implement DescriptorCommon.File()
func (t *EnumValueOptions) File() *FileDescriptorProto {
	if t.Empty() {
		return nil
	}

	return t.getFile()
}

// implement DescriptorCommon.Parent()
func (t *EnumValueOptions) Parent() DescriptorCommon {
	if t.Empty() {
		return nil
	}

	return t.getParent()
}

// implement DescriptorCommon.LocationPath()
func (t *EnumValueOptions) LocationPath() LocationPath {
	if t.Empty() {
		return nil
	}

	return t.getLocationPath()
}
