// Code generated by protoc-gen-goku. DO NOT EDIT.
// source: google/protobuf/descriptor.proto

package descriptors

import (
	bytes "bytes"
	jsonpb "github.com/gogo/protobuf/jsonpb"
	descriptorpb "google.golang.org/protobuf/types/descriptorpb"
)

//   See: descriptorpb.ExtensionRangeOptions
type ExtensionRangeOptions struct {
	common

	pb *descriptorpb.ExtensionRangeOptions

	uninterpreted_option []*UninterpretedOption
}

func newExtensionRangeOptions(desc *descriptorpb.ExtensionRangeOptions) *ExtensionRangeOptions {
	t := new(ExtensionRangeOptions)
	t.pb = desc

	t.setDescriptor(t)

	return t
}

// The parser stores options it doesn't recognize here. See above.
//   See descriptorpb.ExtensionRangeOptions ExtensionRangeOptions.UninterpretedOption
//   SourceCodeInfo.Location.Path: [4 3 2 0]
//   proto info: {"name":"uninterpreted_option","number":999,"label":"LABEL_REPEATED","type":"TYPE_MESSAGE","typeName":".google.protobuf.UninterpretedOption","jsonName":"uninterpretedOption"}
func (t *ExtensionRangeOptions) GetUninterpretedOption() (ret []*UninterpretedOption) {
	if t.Empty() {
		return
	}

	if t.uninterpreted_option != nil {
		return t.uninterpreted_option
	}

	t.uninterpreted_option = make([]*UninterpretedOption, len(t.pb.GetUninterpretedOption()))

	for i, item := range t.pb.GetUninterpretedOption() {
		elem := newUninterpretedOption(item)
		elem.setParent(t)
		elem.setIndex(i)
		t.uninterpreted_option[i] = elem
	}

	return t.uninterpreted_option

}

func (t *ExtensionRangeOptions) UninterpretedOption() []*UninterpretedOption {
	return t.GetUninterpretedOption()
}

func (t *ExtensionRangeOptions) PbDescriptor() *descriptorpb.ExtensionRangeOptions {
	if t == nil || t.pb == nil {
		return nil
	}
	return t.pb
}

func (t *ExtensionRangeOptions) ExtensionRangeOptions() *descriptorpb.ExtensionRangeOptions {
	return t.PbDescriptor()
}

func (t *ExtensionRangeOptions) MarshalJSON() (b []byte, err error) {
	if t.Empty() {
		return
	}
	buf := bytes.NewBuffer(nil)
	err = (&jsonpb.Marshaler{}).Marshal(buf, t.pb)
	return buf.Bytes(), err
}

// implement DescriptorCommon.Empty()
func (t *ExtensionRangeOptions) Empty() bool {
	return t == nil || t.pb == nil
}

// implement DescriptorCommon.Index()
func (t *ExtensionRangeOptions) Index() int {
	if t.Empty() {
		return -1
	}

	return t.getIndex()
}

// implement DescriptorCommon.File()
func (t *ExtensionRangeOptions) File() *FileDescriptorProto {
	if t.Empty() {
		return nil
	}

	return t.getFile()
}

// implement DescriptorCommon.Parent()
func (t *ExtensionRangeOptions) Parent() DescriptorCommon {
	if t.Empty() {
		return nil
	}

	return t.getParent()
}

// implement DescriptorCommon.LocationPath()
func (t *ExtensionRangeOptions) LocationPath() LocationPath {
	if t.Empty() {
		return nil
	}

	return t.getLocationPath()
}
