// Code generated by protoc-gen-goku. DO NOT EDIT.
// source: google/protobuf/descriptor.proto

package descriptors

import (
	descriptorpb "google.golang.org/protobuf/types/descriptorpb"
)

// FieldOptions_JSType
//  See descriptorpb.FieldOptions_JSType
type FieldOptions_JSType = descriptorpb.FieldOptions_JSType

const (
	// Use the default type.
	FieldOptions_JS_NORMAL = descriptorpb.FieldOptions_JS_NORMAL
	// Use JavaScript strings.
	FieldOptions_JS_STRING = descriptorpb.FieldOptions_JS_STRING
	// Use JavaScript numbers.
	FieldOptions_JS_NUMBER = descriptorpb.FieldOptions_JS_NUMBER
)
