// Code generated by protoc-gen-goku. DO NOT EDIT.
// source: google/protobuf/descriptor.proto

package descriptors

import (
	descriptorpb "google.golang.org/protobuf/types/descriptorpb"
)

// FieldDescriptorProto_Label
//  See descriptorpb.FieldDescriptorProto_Label
type FieldDescriptorProto_Label = descriptorpb.FieldDescriptorProto_Label

const (
	// 0 is reserved for errors
	FieldDescriptorProto_LABEL_OPTIONAL = descriptorpb.FieldDescriptorProto_LABEL_OPTIONAL
	FieldDescriptorProto_LABEL_REQUIRED = descriptorpb.FieldDescriptorProto_LABEL_REQUIRED
	FieldDescriptorProto_LABEL_REPEATED = descriptorpb.FieldDescriptorProto_LABEL_REPEATED
)
