// Code generated by protoc-gen-goku. DO NOT EDIT.
// source: google/protobuf/descriptor.proto

package descriptors

import (
	descriptorpb "google.golang.org/protobuf/types/descriptorpb"
)

// FieldOptions_CType
//  See descriptorpb.FieldOptions_CType
type FieldOptions_CType = descriptorpb.FieldOptions_CType

const (
	// Default mode.
	FieldOptions_STRING       = descriptorpb.FieldOptions_STRING
	FieldOptions_CORD         = descriptorpb.FieldOptions_CORD
	FieldOptions_STRING_PIECE = descriptorpb.FieldOptions_STRING_PIECE
)
