// Code generated by protoc-gen-goku. DO NOT EDIT.
// source: google/protobuf/descriptor.proto

package descriptors

import (
	descriptorpb "google.golang.org/protobuf/types/descriptorpb"
)

// FileOptions_OptimizeMode
//  See descriptorpb.FileOptions_OptimizeMode
// Generated classes can be optimized for speed or code size.
type FileOptions_OptimizeMode = descriptorpb.FileOptions_OptimizeMode

const (
	FileOptions_SPEED = descriptorpb.FileOptions_SPEED // Generate complete code for parsing, serialization,
	// etc.
	FileOptions_CODE_SIZE    = descriptorpb.FileOptions_CODE_SIZE    // Use ReflectionOps to implement these methods.
	FileOptions_LITE_RUNTIME = descriptorpb.FileOptions_LITE_RUNTIME // Generate code using MessageLite and the lite runtime.
)
