// Code generated by protoc-gen-goku. DO NOT EDIT.
// source: google/protobuf/descriptor.proto

package descriptors

import (
	bytes "bytes"
	jsonpb "github.com/gogo/protobuf/jsonpb"
	descriptorpb "google.golang.org/protobuf/types/descriptorpb"
)

// Describes a complete .proto file.
//   See: descriptorpb.FileDescriptorProto
type FileDescriptorProto struct {
	common

	pb *descriptorpb.FileDescriptorProto

	message_type []*DescriptorProto

	enum_type []*EnumDescriptorProto

	service []*ServiceDescriptorProto

	extension []*FieldDescriptorProto

	options *FileOptions

	source_code_info *SourceCodeInfo

	locByPath map[string]*SourceCodeInfo_Location
}

func newFileDescriptorProto(desc *descriptorpb.FileDescriptorProto) *FileDescriptorProto {
	t := new(FileDescriptorProto)
	t.pb = desc

	t.setDescriptor(t)

	return t
}

//
// file name, relative to root of source tree
//   See descriptorpb.FileDescriptorProto FileDescriptorProto.Name
//   SourceCodeInfo.Location.Path: [4 1 2 0]
//   proto info: {"name":"name","number":1,"label":"LABEL_OPTIONAL","type":"TYPE_STRING","jsonName":"name"}
func (t *FileDescriptorProto) GetName() (ret string) {
	if t.Empty() {
		return
	}

	return t.pb.GetName()

}

func (t *FileDescriptorProto) Name() string {
	return t.GetName()
}

//
// e.g. "foo", "foo.bar", etc.
//   See descriptorpb.FileDescriptorProto FileDescriptorProto.Package
//   SourceCodeInfo.Location.Path: [4 1 2 1]
//   proto info: {"name":"package","number":2,"label":"LABEL_OPTIONAL","type":"TYPE_STRING","jsonName":"package"}
func (t *FileDescriptorProto) GetPackage() (ret string) {
	if t.Empty() {
		return
	}

	return t.pb.GetPackage()

}

func (t *FileDescriptorProto) Package() string {
	return t.GetPackage()
}

// Names of files imported by this file.
//   See descriptorpb.FileDescriptorProto FileDescriptorProto.Dependency
//   SourceCodeInfo.Location.Path: [4 1 2 2]
//   proto info: {"name":"dependency","number":3,"label":"LABEL_REPEATED","type":"TYPE_STRING","jsonName":"dependency"}
func (t *FileDescriptorProto) GetDependency() (ret []string) {
	if t.Empty() {
		return
	}

	return t.pb.GetDependency()

}

func (t *FileDescriptorProto) Dependency() []string {
	return t.GetDependency()
}

// Indexes of the public imported files in the dependency list above.
//   See descriptorpb.FileDescriptorProto FileDescriptorProto.PublicDependency
//   SourceCodeInfo.Location.Path: [4 1 2 3]
//   proto info: {"name":"public_dependency","number":10,"label":"LABEL_REPEATED","type":"TYPE_INT32","jsonName":"publicDependency"}
func (t *FileDescriptorProto) GetPublicDependency() (ret []int32) {
	if t.Empty() {
		return
	}

	return t.pb.GetPublicDependency()

}

func (t *FileDescriptorProto) PublicDependency() []int32 {
	return t.GetPublicDependency()
}

// Indexes of the weak imported files in the dependency list.
// For Google-internal migration only. Do not use.
//   See descriptorpb.FileDescriptorProto FileDescriptorProto.WeakDependency
//   SourceCodeInfo.Location.Path: [4 1 2 4]
//   proto info: {"name":"weak_dependency","number":11,"label":"LABEL_REPEATED","type":"TYPE_INT32","jsonName":"weakDependency"}
func (t *FileDescriptorProto) GetWeakDependency() (ret []int32) {
	if t.Empty() {
		return
	}

	return t.pb.GetWeakDependency()

}

func (t *FileDescriptorProto) WeakDependency() []int32 {
	return t.GetWeakDependency()
}

// All top-level definitions in this file.
//   See descriptorpb.FileDescriptorProto FileDescriptorProto.MessageType
//   SourceCodeInfo.Location.Path: [4 1 2 5]
//   proto info: {"name":"message_type","number":4,"label":"LABEL_REPEATED","type":"TYPE_MESSAGE","typeName":".google.protobuf.DescriptorProto","jsonName":"messageType"}
func (t *FileDescriptorProto) GetMessageType() (ret []*DescriptorProto) {
	if t.Empty() {
		return
	}

	if t.message_type != nil {
		return t.message_type
	}

	t.message_type = make([]*DescriptorProto, len(t.pb.GetMessageType()))

	for i, item := range t.pb.GetMessageType() {
		elem := newDescriptorProto(item)
		elem.setParent(t)
		elem.setIndex(i)
		t.message_type[i] = elem
	}

	return t.message_type

}

func (t *FileDescriptorProto) MessageType() []*DescriptorProto {
	return t.GetMessageType()
}

//   See descriptorpb.FileDescriptorProto FileDescriptorProto.EnumType
//   SourceCodeInfo.Location.Path: [4 1 2 6]
//   proto info: {"name":"enum_type","number":5,"label":"LABEL_REPEATED","type":"TYPE_MESSAGE","typeName":".google.protobuf.EnumDescriptorProto","jsonName":"enumType"}
func (t *FileDescriptorProto) GetEnumType() (ret []*EnumDescriptorProto) {
	if t.Empty() {
		return
	}

	if t.enum_type != nil {
		return t.enum_type
	}

	t.enum_type = make([]*EnumDescriptorProto, len(t.pb.GetEnumType()))

	for i, item := range t.pb.GetEnumType() {
		elem := newEnumDescriptorProto(item)
		elem.setParent(t)
		elem.setIndex(i)
		t.enum_type[i] = elem
	}

	return t.enum_type

}

func (t *FileDescriptorProto) EnumType() []*EnumDescriptorProto {
	return t.GetEnumType()
}

//   See descriptorpb.FileDescriptorProto FileDescriptorProto.Service
//   SourceCodeInfo.Location.Path: [4 1 2 7]
//   proto info: {"name":"service","number":6,"label":"LABEL_REPEATED","type":"TYPE_MESSAGE","typeName":".google.protobuf.ServiceDescriptorProto","jsonName":"service"}
func (t *FileDescriptorProto) GetService() (ret []*ServiceDescriptorProto) {
	if t.Empty() {
		return
	}

	if t.service != nil {
		return t.service
	}

	t.service = make([]*ServiceDescriptorProto, len(t.pb.GetService()))

	for i, item := range t.pb.GetService() {
		elem := newServiceDescriptorProto(item)
		elem.setParent(t)
		elem.setIndex(i)
		t.service[i] = elem
	}

	return t.service

}

func (t *FileDescriptorProto) Service() []*ServiceDescriptorProto {
	return t.GetService()
}

//   See descriptorpb.FileDescriptorProto FileDescriptorProto.Extension
//   SourceCodeInfo.Location.Path: [4 1 2 8]
//   proto info: {"name":"extension","number":7,"label":"LABEL_REPEATED","type":"TYPE_MESSAGE","typeName":".google.protobuf.FieldDescriptorProto","jsonName":"extension"}
func (t *FileDescriptorProto) GetExtension() (ret []*FieldDescriptorProto) {
	if t.Empty() {
		return
	}

	if t.extension != nil {
		return t.extension
	}

	t.extension = make([]*FieldDescriptorProto, len(t.pb.GetExtension()))

	for i, item := range t.pb.GetExtension() {
		elem := newFieldDescriptorProto(item)
		elem.setParent(t)
		elem.setIndex(i)
		t.extension[i] = elem
	}

	return t.extension

}

func (t *FileDescriptorProto) Extension() []*FieldDescriptorProto {
	return t.GetExtension()
}

//   See descriptorpb.FileDescriptorProto FileDescriptorProto.Options
//   SourceCodeInfo.Location.Path: [4 1 2 9]
//   proto info: {"name":"options","number":8,"label":"LABEL_OPTIONAL","type":"TYPE_MESSAGE","typeName":".google.protobuf.FileOptions","jsonName":"options"}
func (t *FileDescriptorProto) GetOptions() (ret *FileOptions) {
	if t.Empty() {
		return
	}

	if t.options != nil {
		return t.options
	}

	t.options = newFileOptions(t.pb.GetOptions())
	t.options.setParent(t)

	return t.options

}

func (t *FileDescriptorProto) Options() *FileOptions {
	return t.GetOptions()
}

// This field contains optional information about the original source code.
// You may safely remove this entire field without harming runtime
// functionality of the descriptors -- the information is needed only by
// development tools.
//   See descriptorpb.FileDescriptorProto FileDescriptorProto.SourceCodeInfo
//   SourceCodeInfo.Location.Path: [4 1 2 10]
//   proto info: {"name":"source_code_info","number":9,"label":"LABEL_OPTIONAL","type":"TYPE_MESSAGE","typeName":".google.protobuf.SourceCodeInfo","jsonName":"sourceCodeInfo"}
func (t *FileDescriptorProto) GetSourceCodeInfo() (ret *SourceCodeInfo) {
	if t.Empty() {
		return
	}

	if t.source_code_info != nil {
		return t.source_code_info
	}

	t.source_code_info = newSourceCodeInfo(t.pb.GetSourceCodeInfo())
	t.source_code_info.setParent(t)

	return t.source_code_info

}

func (t *FileDescriptorProto) SourceCodeInfo() *SourceCodeInfo {
	return t.GetSourceCodeInfo()
}

// The syntax of the proto file.
// The supported values are "proto2" and "proto3".
//   See descriptorpb.FileDescriptorProto FileDescriptorProto.Syntax
//   SourceCodeInfo.Location.Path: [4 1 2 11]
//   proto info: {"name":"syntax","number":12,"label":"LABEL_OPTIONAL","type":"TYPE_STRING","jsonName":"syntax"}
func (t *FileDescriptorProto) GetSyntax() (ret string) {
	if t.Empty() {
		return
	}

	return t.pb.GetSyntax()

}

func (t *FileDescriptorProto) Syntax() string {
	return t.GetSyntax()
}

func (t *FileDescriptorProto) PbDescriptor() *descriptorpb.FileDescriptorProto {
	if t == nil || t.pb == nil {
		return nil
	}
	return t.pb
}

func (t *FileDescriptorProto) FileDescriptorProto() *descriptorpb.FileDescriptorProto {
	return t.PbDescriptor()
}

func (t *FileDescriptorProto) MarshalJSON() (b []byte, err error) {
	if t.Empty() {
		return
	}
	buf := bytes.NewBuffer(nil)
	err = (&jsonpb.Marshaler{}).Marshal(buf, t.pb)
	return buf.Bytes(), err
}

// implement DescriptorCommon.Empty()
func (t *FileDescriptorProto) Empty() bool {
	return t == nil || t.pb == nil
}

// implement DescriptorCommon.Index()
func (t *FileDescriptorProto) Index() int {
	if t.Empty() {
		return -1
	}

	return t.getIndex()
}

// implement DescriptorCommon.File()
func (t *FileDescriptorProto) File() *FileDescriptorProto {
	if t.Empty() {
		return nil
	}

	return t.getFile()
}

// implement DescriptorCommon.Parent()
func (t *FileDescriptorProto) Parent() DescriptorCommon {
	if t.Empty() {
		return nil
	}

	return t.getParent()
}

// implement DescriptorCommon.LocationPath()
func (t *FileDescriptorProto) LocationPath() LocationPath {
	if t.Empty() {
		return nil
	}

	return t.getLocationPath()
}
