// Code generated by protoc-gen-goku. DO NOT EDIT.
// source: google/protobuf/descriptor.proto

package descriptors

import (
	"google.golang.org/protobuf/types/descriptorpb"
)

// Describes the relationship between generated code and its original source
// file. A GeneratedCodeInfo message is associated with only one generated
// source file, but may contain references to different source .proto files.
//   See: descriptorpb.GeneratedCodeInfo
type GeneratedCodeInfo struct {
	common

	pb *descriptorpb.GeneratedCodeInfo

	annotation []*GeneratedCodeInfo_Annotation
}

func newGeneratedCodeInfo(desc *descriptorpb.GeneratedCodeInfo) *GeneratedCodeInfo {
	t := new(GeneratedCodeInfo)
	t.pb = desc

	t.setDescriptor(t)

	return t
}

// An Annotation connects some span of text in generated code to an element
// of its generating .proto file.
//   See descriptorpb.GeneratedCodeInfo GeneratedCodeInfo.Annotation
//   SourceCodeInfo.Location.Path: [4 20 2 0]
//   proto info: {}
func (t *GeneratedCodeInfo) GetAnnotation() (ret []*GeneratedCodeInfo_Annotation) {
	if t.Empty() {
		return
	}

	if t.annotation != nil {
		return t.annotation
	}

	t.annotation = make([]*GeneratedCodeInfo_Annotation, len(t.pb.GetAnnotation()))

	for i, item := range t.pb.GetAnnotation() {
		elem := newGeneratedCodeInfo_Annotation(item)
		elem.setParent(t)
		elem.setIndex(i)
		t.annotation[i] = elem
	}

	return t.annotation

}

func (t *GeneratedCodeInfo) Annotation() []*GeneratedCodeInfo_Annotation {
	return t.GetAnnotation()
}

func (t *GeneratedCodeInfo) PbDescriptor() *descriptorpb.GeneratedCodeInfo {
	if t == nil || t.pb == nil {
		return nil
	}
	return t.pb
}

func (t *GeneratedCodeInfo) GeneratedCodeInfo() *descriptorpb.GeneratedCodeInfo {
	return t.PbDescriptor()
}

/*
func (t *GeneratedCodeInfo) MarshalJSON() (b []byte,err error) {
    if t.Empty() {
        return
    }
    buf := bytes.NewBuffer(nil)
    err = (&jsonpb.Marshaler{}).Marshal(buf, t.pb)
    return buf.Bytes(), err
}
*/

// ExportFields returns can export fields
func (t *GeneratedCodeInfo) ExportFields() map[string]interface{} {
	return map[string]interface{}{
		"Annotation": t.Annotation(),
	}
}

// implement DescriptorCommon.Empty()
func (t *GeneratedCodeInfo) Empty() bool {
	return t == nil || t.pb == nil
}

// implement DescriptorCommon.Index()
func (t *GeneratedCodeInfo) Index() int {
	if t.Empty() {
		return -1
	}

	return t.getIndex()
}

// implement DescriptorCommon.File()
func (t *GeneratedCodeInfo) File() *FileDescriptorProto {
	if t.Empty() {
		return nil
	}

	return t.getFile()
}

// implement DescriptorCommon.Parent()
func (t *GeneratedCodeInfo) Parent() DescriptorCommon {
	if t.Empty() {
		return nil
	}

	return t.getParent()
}

// implement DescriptorCommon.LocationPath()
func (t *GeneratedCodeInfo) LocationPath() LocationPath {
	if t.Empty() {
		return nil
	}

	return t.getLocationPath()
}

func (t *GeneratedCodeInfo) Comments() *SourceCodeInfo_Location {
	if t.Empty() {
		return nil
	}
	return t.getComments()
}
