// Code generated by protoc-gen-goku. DO NOT EDIT.
// source: google/protobuf/descriptor.proto

package descriptors

import (
	"google.golang.org/protobuf/types/descriptorpb"
)

//   See: descriptorpb.MethodOptions
type MethodOptions struct {
	common

	pb *descriptorpb.MethodOptions

	uninterpreted_option []*UninterpretedOption
}

func newMethodOptions(desc *descriptorpb.MethodOptions) *MethodOptions {
	t := new(MethodOptions)
	t.pb = desc

	t.setDescriptor(t)

	return t
}

// Note:  Field numbers 1 through 32 are reserved for Google's internal RPC
// framework.  We apologize for hoarding these numbers to ourselves, but
// we were already using them long before we decided to release Protocol
// Buffers.  // Is this method deprecated?
// Depending on the target platform, this can emit Deprecated annotations
// for the method, or it will be completely ignored; in the very least,
// this is a formalization for deprecating methods.
//   See descriptorpb.MethodOptions MethodOptions.Deprecated
//   SourceCodeInfo.Location.Path: [4 17 2 0]
//   proto info: {}
func (t *MethodOptions) GetDeprecated() (ret bool) {
	if t.Empty() {
		return
	}

	return t.pb.GetDeprecated()

}

func (t *MethodOptions) Deprecated() bool {
	return t.GetDeprecated()
}

//   See descriptorpb.MethodOptions MethodOptions.IdempotencyLevel
//   SourceCodeInfo.Location.Path: [4 17 2 1]
//   proto info: {}
func (t *MethodOptions) GetIdempotencyLevel() (ret MethodOptions_IdempotencyLevel) {
	if t.Empty() {
		return
	}

	return t.pb.GetIdempotencyLevel()

}

func (t *MethodOptions) IdempotencyLevel() MethodOptions_IdempotencyLevel {
	return t.GetIdempotencyLevel()
}

// The parser stores options it doesn't recognize here. See above.
//   See descriptorpb.MethodOptions MethodOptions.UninterpretedOption
//   SourceCodeInfo.Location.Path: [4 17 2 2]
//   proto info: {}
func (t *MethodOptions) GetUninterpretedOption() (ret []*UninterpretedOption) {
	if t.Empty() {
		return
	}

	if t.uninterpreted_option != nil {
		return t.uninterpreted_option
	}

	t.uninterpreted_option = make([]*UninterpretedOption, len(t.pb.GetUninterpretedOption()))

	for i, item := range t.pb.GetUninterpretedOption() {
		elem := newUninterpretedOption(item)
		elem.setParent(t)
		elem.setIndex(i)
		t.uninterpreted_option[i] = elem
	}

	return t.uninterpreted_option

}

func (t *MethodOptions) UninterpretedOption() []*UninterpretedOption {
	return t.GetUninterpretedOption()
}

func (t *MethodOptions) PbDescriptor() *descriptorpb.MethodOptions {
	if t == nil || t.pb == nil {
		return nil
	}
	return t.pb
}

func (t *MethodOptions) MethodOptions() *descriptorpb.MethodOptions {
	return t.PbDescriptor()
}

/*
func (t *MethodOptions) MarshalJSON() (b []byte,err error) {
    if t.Empty() {
        return
    }
    buf := bytes.NewBuffer(nil)
    err = (&jsonpb.Marshaler{}).Marshal(buf, t.pb)
    return buf.Bytes(), err
}
*/

// ExportFields returns can export fields
func (t *MethodOptions) ExportFields() map[string]interface{} {
	return map[string]interface{}{
		"Deprecated":          t.Deprecated(),
		"IdempotencyLevel":    t.IdempotencyLevel(),
		"UninterpretedOption": t.UninterpretedOption(),
	}
}

// implement DescriptorCommon.Empty()
func (t *MethodOptions) Empty() bool {
	return t == nil || t.pb == nil
}

// implement DescriptorCommon.Index()
func (t *MethodOptions) Index() int {
	if t.Empty() {
		return -1
	}

	return t.getIndex()
}

// implement DescriptorCommon.File()
func (t *MethodOptions) File() *FileDescriptorProto {
	if t.Empty() {
		return nil
	}

	return t.getFile()
}

// implement DescriptorCommon.Parent()
func (t *MethodOptions) Parent() DescriptorCommon {
	if t.Empty() {
		return nil
	}

	return t.getParent()
}

// implement DescriptorCommon.LocationPath()
func (t *MethodOptions) LocationPath() LocationPath {
	if t.Empty() {
		return nil
	}

	return t.getLocationPath()
}

func (t *MethodOptions) Comments() *SourceCodeInfo_Location {
	if t.Empty() {
		return nil
	}
	return t.getComments()
}
