// Code generated by protoc-gen-goku. DO NOT EDIT.
// source: google/protobuf/descriptor.proto

package descriptors

import (
	"google.golang.org/protobuf/types/descriptorpb"
)

// MethodOptions_IdempotencyLevel
//  See descriptorpb.MethodOptions_IdempotencyLevel
// Is this method side-effect-free (or safe in HTTP parlance), or idempotent,
// or neither? HTTP based RPC implementation may choose GET verb for safe
// methods, and PUT verb for idempotent methods instead of the default POST.
type MethodOptions_IdempotencyLevel = descriptorpb.MethodOptions_IdempotencyLevel

const (
	MethodOptions_IDEMPOTENCY_UNKNOWN = descriptorpb.MethodOptions_IDEMPOTENCY_UNKNOWN
	MethodOptions_NO_SIDE_EFFECTS     = descriptorpb.MethodOptions_NO_SIDE_EFFECTS // implies idempotent
	MethodOptions_IDEMPOTENT          = descriptorpb.MethodOptions_IDEMPOTENT      // idempotent, but may have side effects
)
