// Code generated by protoc-gen-goku. DO NOT EDIT.
// source: google/protobuf/descriptor.proto

package descriptors

import (
	"google.golang.org/protobuf/types/descriptorpb"
)

//   See: descriptorpb.OneofOptions
type OneofOptions struct {
	common

	pb *descriptorpb.OneofOptions

	uninterpreted_option []*UninterpretedOption
}

func newOneofOptions(desc *descriptorpb.OneofOptions) *OneofOptions {
	t := new(OneofOptions)
	t.pb = desc

	t.setDescriptor(t)

	return t
}

// The parser stores options it doesn't recognize here. See above.
//   See descriptorpb.OneofOptions OneofOptions.UninterpretedOption
//   SourceCodeInfo.Location.Path: [4 13 2 0]
//   proto info: {}
func (t *OneofOptions) GetUninterpretedOption() (ret []*UninterpretedOption) {
	if t.Empty() {
		return
	}

	if t.uninterpreted_option != nil {
		return t.uninterpreted_option
	}

	t.uninterpreted_option = make([]*UninterpretedOption, len(t.pb.GetUninterpretedOption()))

	for i, item := range t.pb.GetUninterpretedOption() {
		elem := newUninterpretedOption(item)
		elem.setParent(t)
		elem.setIndex(i)
		t.uninterpreted_option[i] = elem
	}

	return t.uninterpreted_option

}

func (t *OneofOptions) UninterpretedOption() []*UninterpretedOption {
	return t.GetUninterpretedOption()
}

func (t *OneofOptions) PbDescriptor() *descriptorpb.OneofOptions {
	if t == nil || t.pb == nil {
		return nil
	}
	return t.pb
}

func (t *OneofOptions) OneofOptions() *descriptorpb.OneofOptions {
	return t.PbDescriptor()
}

/*
func (t *OneofOptions) MarshalJSON() (b []byte,err error) {
    if t.Empty() {
        return
    }
    buf := bytes.NewBuffer(nil)
    err = (&jsonpb.Marshaler{}).Marshal(buf, t.pb)
    return buf.Bytes(), err
}
*/

// ExportFields returns can export fields
func (t *OneofOptions) ExportFields() map[string]interface{} {
	return map[string]interface{}{
		"UninterpretedOption": t.UninterpretedOption(),
	}
}

// implement DescriptorCommon.Empty()
func (t *OneofOptions) Empty() bool {
	return t == nil || t.pb == nil
}

// implement DescriptorCommon.Index()
func (t *OneofOptions) Index() int {
	if t.Empty() {
		return -1
	}

	return t.getIndex()
}

// implement DescriptorCommon.File()
func (t *OneofOptions) File() *FileDescriptorProto {
	if t.Empty() {
		return nil
	}

	return t.getFile()
}

// implement DescriptorCommon.Parent()
func (t *OneofOptions) Parent() DescriptorCommon {
	if t.Empty() {
		return nil
	}

	return t.getParent()
}

// implement DescriptorCommon.LocationPath()
func (t *OneofOptions) LocationPath() LocationPath {
	if t.Empty() {
		return nil
	}

	return t.getLocationPath()
}

func (t *OneofOptions) Comments() *SourceCodeInfo_Location {
	if t.Empty() {
		return nil
	}
	return t.getComments()
}
