// Code generated by protoc-gen-go. DO NOT EDIT.
// source: posts/posts.proto

package proto_posts

import (
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	_ "github.com/golang/protobuf/ptypes/empty"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

type Post struct {
	Id                   string            `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	Title                string            `protobuf:"bytes,2,opt,name=title,proto3" json:"title,omitempty"`
	Slug                 string            `protobuf:"bytes,3,opt,name=slug,proto3" json:"slug,omitempty"`
	Content              string            `protobuf:"bytes,4,opt,name=content,proto3" json:"content,omitempty"`
	Created              int64             `protobuf:"varint,5,opt,name=created,proto3" json:"created,omitempty"`
	Updated              int64             `protobuf:"varint,6,opt,name=updated,proto3" json:"updated,omitempty"`
	Author               string            `protobuf:"bytes,7,opt,name=author,proto3" json:"author,omitempty"`
	Tags                 []string          `protobuf:"bytes,8,rep,name=tags,proto3" json:"tags,omitempty"`
	Metadata             map[string]string `protobuf:"bytes,9,rep,name=metadata,proto3" json:"metadata,omitempty" protobuf_key:"bytes,1,opt,name=key,proto3" protobuf_val:"bytes,2,opt,name=value,proto3"`
	Image                string            `protobuf:"bytes,19,opt,name=image,proto3" json:"image,omitempty"`
	XXX_NoUnkeyedLiteral struct{}          `json:"-"`
	XXX_unrecognized     []byte            `json:"-"`
	XXX_sizecache        int32             `json:"-"`
}

func (m *Post) Reset()         { *m = Post{} }
func (m *Post) String() string { return proto.CompactTextString(m) }
func (*Post) ProtoMessage()    {}
func (*Post) Descriptor() ([]byte, []int) {
	return fileDescriptor_cb373daedc9f9f50, []int{0}
}

func (m *Post) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Post.Unmarshal(m, b)
}
func (m *Post) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Post.Marshal(b, m, deterministic)
}
func (m *Post) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Post.Merge(m, src)
}
func (m *Post) XXX_Size() int {
	return xxx_messageInfo_Post.Size(m)
}
func (m *Post) XXX_DiscardUnknown() {
	xxx_messageInfo_Post.DiscardUnknown(m)
}

var xxx_messageInfo_Post proto.InternalMessageInfo

func (m *Post) GetId() string {
	if m != nil {
		return m.Id
	}
	return ""
}

func (m *Post) GetTitle() string {
	if m != nil {
		return m.Title
	}
	return ""
}

func (m *Post) GetSlug() string {
	if m != nil {
		return m.Slug
	}
	return ""
}

func (m *Post) GetContent() string {
	if m != nil {
		return m.Content
	}
	return ""
}

func (m *Post) GetCreated() int64 {
	if m != nil {
		return m.Created
	}
	return 0
}

func (m *Post) GetUpdated() int64 {
	if m != nil {
		return m.Updated
	}
	return 0
}

func (m *Post) GetAuthor() string {
	if m != nil {
		return m.Author
	}
	return ""
}

func (m *Post) GetTags() []string {
	if m != nil {
		return m.Tags
	}
	return nil
}

func (m *Post) GetMetadata() map[string]string {
	if m != nil {
		return m.Metadata
	}
	return nil
}

func (m *Post) GetImage() string {
	if m != nil {
		return m.Image
	}
	return ""
}

// Query posts. Acts as a listing when no id or slug provided.
// Gets a single post by id or slug if any of them provided.
type QueryRequest struct {
	Id                   string   `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	Slug                 string   `protobuf:"bytes,2,opt,name=slug,proto3" json:"slug,omitempty"`
	Tag                  string   `protobuf:"bytes,3,opt,name=tag,proto3" json:"tag,omitempty"`
	Offset               int64    `protobuf:"varint,4,opt,name=offset,proto3" json:"offset,omitempty"`
	Limit                int64    `protobuf:"varint,5,opt,name=limit,proto3" json:"limit,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *QueryRequest) Reset()         { *m = QueryRequest{} }
func (m *QueryRequest) String() string { return proto.CompactTextString(m) }
func (*QueryRequest) ProtoMessage()    {}
func (*QueryRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_cb373daedc9f9f50, []int{1}
}

func (m *QueryRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_QueryRequest.Unmarshal(m, b)
}
func (m *QueryRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_QueryRequest.Marshal(b, m, deterministic)
}
func (m *QueryRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_QueryRequest.Merge(m, src)
}
func (m *QueryRequest) XXX_Size() int {
	return xxx_messageInfo_QueryRequest.Size(m)
}
func (m *QueryRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_QueryRequest.DiscardUnknown(m)
}

var xxx_messageInfo_QueryRequest proto.InternalMessageInfo

func (m *QueryRequest) GetId() string {
	if m != nil {
		return m.Id
	}
	return ""
}

func (m *QueryRequest) GetSlug() string {
	if m != nil {
		return m.Slug
	}
	return ""
}

func (m *QueryRequest) GetTag() string {
	if m != nil {
		return m.Tag
	}
	return ""
}

func (m *QueryRequest) GetOffset() int64 {
	if m != nil {
		return m.Offset
	}
	return 0
}

func (m *QueryRequest) GetLimit() int64 {
	if m != nil {
		return m.Limit
	}
	return 0
}

type QueryResponse struct {
	Posts                []*Post  `protobuf:"bytes,1,rep,name=posts,proto3" json:"posts,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *QueryResponse) Reset()         { *m = QueryResponse{} }
func (m *QueryResponse) String() string { return proto.CompactTextString(m) }
func (*QueryResponse) ProtoMessage()    {}
func (*QueryResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_cb373daedc9f9f50, []int{2}
}

func (m *QueryResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_QueryResponse.Unmarshal(m, b)
}
func (m *QueryResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_QueryResponse.Marshal(b, m, deterministic)
}
func (m *QueryResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_QueryResponse.Merge(m, src)
}
func (m *QueryResponse) XXX_Size() int {
	return xxx_messageInfo_QueryResponse.Size(m)
}
func (m *QueryResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_QueryResponse.DiscardUnknown(m)
}

var xxx_messageInfo_QueryResponse proto.InternalMessageInfo

func (m *QueryResponse) GetPosts() []*Post {
	if m != nil {
		return m.Posts
	}
	return nil
}

type SaveRequest struct {
	Id        string `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	Title     string `protobuf:"bytes,2,opt,name=title,proto3" json:"title,omitempty"`
	Slug      string `protobuf:"bytes,3,opt,name=slug,proto3" json:"slug,omitempty"`
	Content   string `protobuf:"bytes,4,opt,name=content,proto3" json:"content,omitempty"`
	Timestamp int64  `protobuf:"varint,5,opt,name=timestamp,proto3" json:"timestamp,omitempty"`
	// When updating a post and wanting to delete all tags,
	// send a list of tags with only one member being an empty string [""]
	Tags                 []string          `protobuf:"bytes,6,rep,name=tags,proto3" json:"tags,omitempty"`
	Metadata             map[string]string `protobuf:"bytes,7,rep,name=metadata,proto3" json:"metadata,omitempty" protobuf_key:"bytes,1,opt,name=key,proto3" protobuf_val:"bytes,2,opt,name=value,proto3"`
	Image                string            `protobuf:"bytes,8,opt,name=image,proto3" json:"image,omitempty"`
	XXX_NoUnkeyedLiteral struct{}          `json:"-"`
	XXX_unrecognized     []byte            `json:"-"`
	XXX_sizecache        int32             `json:"-"`
}

func (m *SaveRequest) Reset()         { *m = SaveRequest{} }
func (m *SaveRequest) String() string { return proto.CompactTextString(m) }
func (*SaveRequest) ProtoMessage()    {}
func (*SaveRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_cb373daedc9f9f50, []int{3}
}

func (m *SaveRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_SaveRequest.Unmarshal(m, b)
}
func (m *SaveRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_SaveRequest.Marshal(b, m, deterministic)
}
func (m *SaveRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_SaveRequest.Merge(m, src)
}
func (m *SaveRequest) XXX_Size() int {
	return xxx_messageInfo_SaveRequest.Size(m)
}
func (m *SaveRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_SaveRequest.DiscardUnknown(m)
}

var xxx_messageInfo_SaveRequest proto.InternalMessageInfo

func (m *SaveRequest) GetId() string {
	if m != nil {
		return m.Id
	}
	return ""
}

func (m *SaveRequest) GetTitle() string {
	if m != nil {
		return m.Title
	}
	return ""
}

func (m *SaveRequest) GetSlug() string {
	if m != nil {
		return m.Slug
	}
	return ""
}

func (m *SaveRequest) GetContent() string {
	if m != nil {
		return m.Content
	}
	return ""
}

func (m *SaveRequest) GetTimestamp() int64 {
	if m != nil {
		return m.Timestamp
	}
	return 0
}

func (m *SaveRequest) GetTags() []string {
	if m != nil {
		return m.Tags
	}
	return nil
}

func (m *SaveRequest) GetMetadata() map[string]string {
	if m != nil {
		return m.Metadata
	}
	return nil
}

func (m *SaveRequest) GetImage() string {
	if m != nil {
		return m.Image
	}
	return ""
}

type SaveResponse struct {
	Id                   string   `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *SaveResponse) Reset()         { *m = SaveResponse{} }
func (m *SaveResponse) String() string { return proto.CompactTextString(m) }
func (*SaveResponse) ProtoMessage()    {}
func (*SaveResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_cb373daedc9f9f50, []int{4}
}

func (m *SaveResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_SaveResponse.Unmarshal(m, b)
}
func (m *SaveResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_SaveResponse.Marshal(b, m, deterministic)
}
func (m *SaveResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_SaveResponse.Merge(m, src)
}
func (m *SaveResponse) XXX_Size() int {
	return xxx_messageInfo_SaveResponse.Size(m)
}
func (m *SaveResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_SaveResponse.DiscardUnknown(m)
}

var xxx_messageInfo_SaveResponse proto.InternalMessageInfo

func (m *SaveResponse) GetId() string {
	if m != nil {
		return m.Id
	}
	return ""
}

type DeleteRequest struct {
	Id                   string   `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *DeleteRequest) Reset()         { *m = DeleteRequest{} }
func (m *DeleteRequest) String() string { return proto.CompactTextString(m) }
func (*DeleteRequest) ProtoMessage()    {}
func (*DeleteRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_cb373daedc9f9f50, []int{5}
}

func (m *DeleteRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_DeleteRequest.Unmarshal(m, b)
}
func (m *DeleteRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_DeleteRequest.Marshal(b, m, deterministic)
}
func (m *DeleteRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_DeleteRequest.Merge(m, src)
}
func (m *DeleteRequest) XXX_Size() int {
	return xxx_messageInfo_DeleteRequest.Size(m)
}
func (m *DeleteRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_DeleteRequest.DiscardUnknown(m)
}

var xxx_messageInfo_DeleteRequest proto.InternalMessageInfo

func (m *DeleteRequest) GetId() string {
	if m != nil {
		return m.Id
	}
	return ""
}

type DeleteResponse struct {
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *DeleteResponse) Reset()         { *m = DeleteResponse{} }
func (m *DeleteResponse) String() string { return proto.CompactTextString(m) }
func (*DeleteResponse) ProtoMessage()    {}
func (*DeleteResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_cb373daedc9f9f50, []int{6}
}

func (m *DeleteResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_DeleteResponse.Unmarshal(m, b)
}
func (m *DeleteResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_DeleteResponse.Marshal(b, m, deterministic)
}
func (m *DeleteResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_DeleteResponse.Merge(m, src)
}
func (m *DeleteResponse) XXX_Size() int {
	return xxx_messageInfo_DeleteResponse.Size(m)
}
func (m *DeleteResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_DeleteResponse.DiscardUnknown(m)
}

var xxx_messageInfo_DeleteResponse proto.InternalMessageInfo

type ReportRequest struct {
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *ReportRequest) Reset()         { *m = ReportRequest{} }
func (m *ReportRequest) String() string { return proto.CompactTextString(m) }
func (*ReportRequest) ProtoMessage()    {}
func (*ReportRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_cb373daedc9f9f50, []int{7}
}

func (m *ReportRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ReportRequest.Unmarshal(m, b)
}
func (m *ReportRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ReportRequest.Marshal(b, m, deterministic)
}
func (m *ReportRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ReportRequest.Merge(m, src)
}
func (m *ReportRequest) XXX_Size() int {
	return xxx_messageInfo_ReportRequest.Size(m)
}
func (m *ReportRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_ReportRequest.DiscardUnknown(m)
}

var xxx_messageInfo_ReportRequest proto.InternalMessageInfo

func init() {
	proto.RegisterType((*Post)(nil), "posts.Post")
	proto.RegisterMapType((map[string]string)(nil), "posts.Post.MetadataEntry")
	proto.RegisterType((*QueryRequest)(nil), "posts.QueryRequest")
	proto.RegisterType((*QueryResponse)(nil), "posts.QueryResponse")
	proto.RegisterType((*SaveRequest)(nil), "posts.SaveRequest")
	proto.RegisterMapType((map[string]string)(nil), "posts.SaveRequest.MetadataEntry")
	proto.RegisterType((*SaveResponse)(nil), "posts.SaveResponse")
	proto.RegisterType((*DeleteRequest)(nil), "posts.DeleteRequest")
	proto.RegisterType((*DeleteResponse)(nil), "posts.DeleteResponse")
	proto.RegisterType((*ReportRequest)(nil), "posts.ReportRequest")
}

func init() { proto.RegisterFile("posts/posts.proto", fileDescriptor_cb373daedc9f9f50) }

var fileDescriptor_cb373daedc9f9f50 = []byte{
	// 556 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0xac, 0x54, 0xcd, 0x6e, 0xd3, 0x40,
	0x10, 0xae, 0xed, 0xc4, 0x6d, 0x26, 0x4d, 0x09, 0x9b, 0x52, 0x19, 0x83, 0x20, 0xf8, 0x94, 0x4b,
	0x6d, 0x1a, 0x40, 0xb4, 0x94, 0x13, 0xa2, 0x07, 0x84, 0x90, 0xc0, 0xdc, 0xb8, 0xa0, 0x4d, 0x32,
	0x71, 0xad, 0xda, 0x59, 0xe3, 0x5d, 0x47, 0xe4, 0x7d, 0x78, 0x14, 0xde, 0x84, 0x17, 0x41, 0xfb,
	0x63, 0xe3, 0x14, 0x2a, 0x2e, 0xbd, 0x58, 0xf3, 0xcd, 0xec, 0xfc, 0x7d, 0x9f, 0x35, 0x70, 0xb7,
	0x60, 0x5c, 0xf0, 0x48, 0x7d, 0xc3, 0xa2, 0x64, 0x82, 0x91, 0xae, 0x02, 0xfe, 0x83, 0x84, 0xb1,
	0x24, 0xc3, 0x48, 0x39, 0x67, 0xd5, 0x32, 0xc2, 0xbc, 0x10, 0x1b, 0xfd, 0x26, 0xf8, 0x69, 0x43,
	0xe7, 0x23, 0xe3, 0x82, 0x1c, 0x80, 0x9d, 0x2e, 0x3c, 0x6b, 0x6c, 0x4d, 0x7a, 0xb1, 0x9d, 0x2e,
	0xc8, 0x21, 0x74, 0x45, 0x2a, 0x32, 0xf4, 0x6c, 0xe5, 0xd2, 0x80, 0x10, 0xe8, 0xf0, 0xac, 0x4a,
	0x3c, 0x47, 0x39, 0x95, 0x4d, 0x3c, 0xd8, 0x9d, 0xb3, 0x95, 0xc0, 0x95, 0xf0, 0x3a, 0xca, 0x5d,
	0x43, 0x15, 0x29, 0x91, 0x0a, 0x5c, 0x78, 0xdd, 0xb1, 0x35, 0x71, 0xe2, 0x1a, 0xca, 0x48, 0x55,
	0x2c, 0x54, 0xc4, 0xd5, 0x11, 0x03, 0xc9, 0x11, 0xb8, 0xb4, 0x12, 0x97, 0xac, 0xf4, 0x76, 0x55,
	0x31, 0x83, 0x64, 0x67, 0x41, 0x13, 0xee, 0xed, 0x8d, 0x1d, 0xd9, 0x59, 0xda, 0xe4, 0x05, 0xec,
	0xe5, 0x28, 0xe8, 0x82, 0x0a, 0xea, 0xf5, 0xc6, 0xce, 0xa4, 0x3f, 0xbd, 0x1f, 0x6a, 0x02, 0xe4,
	0x4a, 0xe1, 0x07, 0x13, 0xbb, 0x58, 0x89, 0x72, 0x13, 0x37, 0x4f, 0xe5, 0x6a, 0x69, 0x4e, 0x13,
	0xf4, 0x46, 0x7a, 0x35, 0x05, 0xfc, 0x73, 0x18, 0x6c, 0x25, 0x90, 0x21, 0x38, 0x57, 0xb8, 0x31,
	0x94, 0x48, 0x53, 0x26, 0xae, 0x69, 0x56, 0x35, 0x9c, 0x28, 0xf0, 0xca, 0x3e, 0xb5, 0x82, 0x12,
	0xf6, 0x3f, 0x55, 0x58, 0x6e, 0x62, 0xfc, 0x56, 0xe1, 0x3f, 0xd8, 0xac, 0x79, 0xb3, 0x5b, 0xbc,
	0x0d, 0xc1, 0x11, 0xb4, 0xa6, 0x52, 0x9a, 0x72, 0x77, 0xb6, 0x5c, 0x72, 0xd4, 0x44, 0x3a, 0xb1,
	0x41, 0xb2, 0x6f, 0x96, 0xe6, 0xa9, 0x30, 0x2c, 0x6a, 0x10, 0x4c, 0x61, 0x60, 0x7a, 0xf2, 0x82,
	0xad, 0x38, 0x92, 0x27, 0xa0, 0x15, 0xf7, 0x2c, 0xc5, 0x45, 0xbf, 0xc5, 0x45, 0xac, 0x23, 0xc1,
	0x0f, 0x1b, 0xfa, 0x9f, 0xe9, 0x1a, 0x6f, 0x9a, 0xf3, 0x36, 0x54, 0x7f, 0x08, 0x3d, 0x91, 0xe6,
	0xc8, 0x05, 0xcd, 0x0b, 0x33, 0xf1, 0x1f, 0x47, 0xa3, 0xa3, 0xdb, 0xd2, 0xf1, 0x75, 0x4b, 0xc7,
	0x5d, 0x35, 0xfb, 0xd8, 0xcc, 0xde, 0x9a, 0xf5, 0xff, 0x72, 0xee, 0xdd, 0x9a, 0x9c, 0x8f, 0x60,
	0x5f, 0x77, 0x36, 0xcc, 0x5e, 0xa3, 0x29, 0x78, 0x0c, 0x83, 0xb7, 0x98, 0xa1, 0xb8, 0x89, 0xc7,
	0x60, 0x08, 0x07, 0xf5, 0x03, 0x5d, 0x22, 0xb8, 0x03, 0x83, 0x18, 0x0b, 0x56, 0x0a, 0x93, 0x32,
	0xfd, 0x65, 0x41, 0x57, 0x4a, 0xc3, 0xc9, 0x73, 0xe8, 0x2a, 0x21, 0xc9, 0xc8, 0x6c, 0xdd, 0xfe,
	0x95, 0xfc, 0xc3, 0x6d, 0xa7, 0x29, 0xb7, 0x43, 0x4e, 0xa0, 0x23, 0x67, 0x24, 0xe4, 0x6f, 0xaa,
	0xfc, 0xd1, 0x96, 0xaf, 0x49, 0x79, 0x09, 0xae, 0x9e, 0x8a, 0xd4, 0x45, 0xb7, 0xb6, 0xf0, 0xef,
	0x5d, 0xf3, 0x36, 0x89, 0xa7, 0xe0, 0xea, 0xe1, 0x9b, 0xc4, 0xad, 0x5d, 0xfc, 0xa3, 0x50, 0xdf,
	0x98, 0xb0, 0xbe, 0x31, 0xe1, 0x85, 0xbc, 0x31, 0xc1, 0xce, 0x9b, 0xf7, 0x5f, 0xde, 0x25, 0xa9,
	0xb8, 0xac, 0x66, 0xe1, 0x9c, 0xe5, 0xd1, 0xfa, 0xe4, 0xec, 0xec, 0xa9, 0x3e, 0x44, 0xf3, 0xe3,
	0x04, 0x57, 0xc7, 0x09, 0xbb, 0xaa, 0x22, 0xfc, 0x4e, 0xf3, 0x22, 0x43, 0x1e, 0xcd, 0x32, 0x96,
	0xe8, 0xe8, 0xd7, 0x84, 0xe9, 0x53, 0x76, 0xae, 0xa1, 0xb2, 0x67, 0xae, 0x02, 0xcf, 0x7e, 0x07,
	0x00, 0x00, 0xff, 0xff, 0x73, 0x1f, 0xb3, 0x10, 0xec, 0x04, 0x00, 0x00,
}
