// Code generated by protoc-gen-go. DO NOT EDIT.
// source: order/order.proto

package proto_order

import (
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	common "github.com/v1990/protoc-gen-goku/examples/eshop/proto/out_go/common"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

// 订单状态
type OrderStatus int32

const (
	OrderStatus_OrderStatusNone OrderStatus = 0
	OrderStatus_Submitted       OrderStatus = 10
	OrderStatus_Created         OrderStatus = 20
	OrderStatus_Paid            OrderStatus = 40
	OrderStatus_Received        OrderStatus = 80
	OrderStatus_Canceled        OrderStatus = 98
	OrderStatus_Failed          OrderStatus = 99
)

var OrderStatus_name = map[int32]string{
	0:  "OrderStatusNone",
	10: "Submitted",
	20: "Created",
	40: "Paid",
	80: "Received",
	98: "Canceled",
	99: "Failed",
}

var OrderStatus_value = map[string]int32{
	"OrderStatusNone": 0,
	"Submitted":       10,
	"Created":         20,
	"Paid":            40,
	"Received":        80,
	"Canceled":        98,
	"Failed":          99,
}

func (x OrderStatus) String() string {
	return proto.EnumName(OrderStatus_name, int32(x))
}

func (OrderStatus) EnumDescriptor() ([]byte, []int) {
	return fileDescriptor_fa47a2077d8980ed, []int{0}
}

type CreateOrderReq struct {
	Head                 *common.ReqHead   `protobuf:"bytes,1,opt,name=head,proto3" json:"head,omitempty"`
	Token                *common.AuthToken `protobuf:"bytes,2,opt,name=token,proto3" json:"token,omitempty"`
	ItemID               uint64            `protobuf:"varint,3,opt,name=itemID,proto3" json:"itemID,omitempty"`
	AddressID            uint64            `protobuf:"varint,4,opt,name=addressID,proto3" json:"addressID,omitempty"`
	XXX_NoUnkeyedLiteral struct{}          `json:"-"`
	XXX_unrecognized     []byte            `json:"-"`
	XXX_sizecache        int32             `json:"-"`
}

func (m *CreateOrderReq) Reset()         { *m = CreateOrderReq{} }
func (m *CreateOrderReq) String() string { return proto.CompactTextString(m) }
func (*CreateOrderReq) ProtoMessage()    {}
func (*CreateOrderReq) Descriptor() ([]byte, []int) {
	return fileDescriptor_fa47a2077d8980ed, []int{0}
}

func (m *CreateOrderReq) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_CreateOrderReq.Unmarshal(m, b)
}
func (m *CreateOrderReq) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_CreateOrderReq.Marshal(b, m, deterministic)
}
func (m *CreateOrderReq) XXX_Merge(src proto.Message) {
	xxx_messageInfo_CreateOrderReq.Merge(m, src)
}
func (m *CreateOrderReq) XXX_Size() int {
	return xxx_messageInfo_CreateOrderReq.Size(m)
}
func (m *CreateOrderReq) XXX_DiscardUnknown() {
	xxx_messageInfo_CreateOrderReq.DiscardUnknown(m)
}

var xxx_messageInfo_CreateOrderReq proto.InternalMessageInfo

func (m *CreateOrderReq) GetHead() *common.ReqHead {
	if m != nil {
		return m.Head
	}
	return nil
}

func (m *CreateOrderReq) GetToken() *common.AuthToken {
	if m != nil {
		return m.Token
	}
	return nil
}

func (m *CreateOrderReq) GetItemID() uint64 {
	if m != nil {
		return m.ItemID
	}
	return 0
}

func (m *CreateOrderReq) GetAddressID() uint64 {
	if m != nil {
		return m.AddressID
	}
	return 0
}

type CreateOrderResp struct {
	Head                 *common.RespHead `protobuf:"bytes,1,opt,name=head,proto3" json:"head,omitempty"`
	Err                  *common.Error    `protobuf:"bytes,2,opt,name=err,proto3" json:"err,omitempty"`
	OrderID              uint64           `protobuf:"varint,3,opt,name=orderID,proto3" json:"orderID,omitempty"`
	XXX_NoUnkeyedLiteral struct{}         `json:"-"`
	XXX_unrecognized     []byte           `json:"-"`
	XXX_sizecache        int32            `json:"-"`
}

func (m *CreateOrderResp) Reset()         { *m = CreateOrderResp{} }
func (m *CreateOrderResp) String() string { return proto.CompactTextString(m) }
func (*CreateOrderResp) ProtoMessage()    {}
func (*CreateOrderResp) Descriptor() ([]byte, []int) {
	return fileDescriptor_fa47a2077d8980ed, []int{1}
}

func (m *CreateOrderResp) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_CreateOrderResp.Unmarshal(m, b)
}
func (m *CreateOrderResp) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_CreateOrderResp.Marshal(b, m, deterministic)
}
func (m *CreateOrderResp) XXX_Merge(src proto.Message) {
	xxx_messageInfo_CreateOrderResp.Merge(m, src)
}
func (m *CreateOrderResp) XXX_Size() int {
	return xxx_messageInfo_CreateOrderResp.Size(m)
}
func (m *CreateOrderResp) XXX_DiscardUnknown() {
	xxx_messageInfo_CreateOrderResp.DiscardUnknown(m)
}

var xxx_messageInfo_CreateOrderResp proto.InternalMessageInfo

func (m *CreateOrderResp) GetHead() *common.RespHead {
	if m != nil {
		return m.Head
	}
	return nil
}

func (m *CreateOrderResp) GetErr() *common.Error {
	if m != nil {
		return m.Err
	}
	return nil
}

func (m *CreateOrderResp) GetOrderID() uint64 {
	if m != nil {
		return m.OrderID
	}
	return 0
}

type OrderDetailReq struct {
	Head                 *common.ReqHead   `protobuf:"bytes,1,opt,name=head,proto3" json:"head,omitempty"`
	Token                *common.AuthToken `protobuf:"bytes,2,opt,name=token,proto3" json:"token,omitempty"`
	OrderID              uint64            `protobuf:"varint,3,opt,name=orderID,proto3" json:"orderID,omitempty"`
	XXX_NoUnkeyedLiteral struct{}          `json:"-"`
	XXX_unrecognized     []byte            `json:"-"`
	XXX_sizecache        int32             `json:"-"`
}

func (m *OrderDetailReq) Reset()         { *m = OrderDetailReq{} }
func (m *OrderDetailReq) String() string { return proto.CompactTextString(m) }
func (*OrderDetailReq) ProtoMessage()    {}
func (*OrderDetailReq) Descriptor() ([]byte, []int) {
	return fileDescriptor_fa47a2077d8980ed, []int{2}
}

func (m *OrderDetailReq) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_OrderDetailReq.Unmarshal(m, b)
}
func (m *OrderDetailReq) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_OrderDetailReq.Marshal(b, m, deterministic)
}
func (m *OrderDetailReq) XXX_Merge(src proto.Message) {
	xxx_messageInfo_OrderDetailReq.Merge(m, src)
}
func (m *OrderDetailReq) XXX_Size() int {
	return xxx_messageInfo_OrderDetailReq.Size(m)
}
func (m *OrderDetailReq) XXX_DiscardUnknown() {
	xxx_messageInfo_OrderDetailReq.DiscardUnknown(m)
}

var xxx_messageInfo_OrderDetailReq proto.InternalMessageInfo

func (m *OrderDetailReq) GetHead() *common.ReqHead {
	if m != nil {
		return m.Head
	}
	return nil
}

func (m *OrderDetailReq) GetToken() *common.AuthToken {
	if m != nil {
		return m.Token
	}
	return nil
}

func (m *OrderDetailReq) GetOrderID() uint64 {
	if m != nil {
		return m.OrderID
	}
	return 0
}

type OrderDetailResp struct {
	Head                 *common.RespHead `protobuf:"bytes,1,opt,name=head,proto3" json:"head,omitempty"`
	Err                  *common.Error    `protobuf:"bytes,2,opt,name=err,proto3" json:"err,omitempty"`
	OrderID              uint64           `protobuf:"varint,3,opt,name=orderID,proto3" json:"orderID,omitempty"`
	ItemID               uint64           `protobuf:"varint,4,opt,name=itemID,proto3" json:"itemID,omitempty"`
	AddressID            uint64           `protobuf:"varint,5,opt,name=addressID,proto3" json:"addressID,omitempty"`
	OrderStatus          OrderStatus      `protobuf:"varint,7,opt,name=orderStatus,proto3,enum=order.OrderStatus" json:"orderStatus,omitempty"`
	XXX_NoUnkeyedLiteral struct{}         `json:"-"`
	XXX_unrecognized     []byte           `json:"-"`
	XXX_sizecache        int32            `json:"-"`
}

func (m *OrderDetailResp) Reset()         { *m = OrderDetailResp{} }
func (m *OrderDetailResp) String() string { return proto.CompactTextString(m) }
func (*OrderDetailResp) ProtoMessage()    {}
func (*OrderDetailResp) Descriptor() ([]byte, []int) {
	return fileDescriptor_fa47a2077d8980ed, []int{3}
}

func (m *OrderDetailResp) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_OrderDetailResp.Unmarshal(m, b)
}
func (m *OrderDetailResp) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_OrderDetailResp.Marshal(b, m, deterministic)
}
func (m *OrderDetailResp) XXX_Merge(src proto.Message) {
	xxx_messageInfo_OrderDetailResp.Merge(m, src)
}
func (m *OrderDetailResp) XXX_Size() int {
	return xxx_messageInfo_OrderDetailResp.Size(m)
}
func (m *OrderDetailResp) XXX_DiscardUnknown() {
	xxx_messageInfo_OrderDetailResp.DiscardUnknown(m)
}

var xxx_messageInfo_OrderDetailResp proto.InternalMessageInfo

func (m *OrderDetailResp) GetHead() *common.RespHead {
	if m != nil {
		return m.Head
	}
	return nil
}

func (m *OrderDetailResp) GetErr() *common.Error {
	if m != nil {
		return m.Err
	}
	return nil
}

func (m *OrderDetailResp) GetOrderID() uint64 {
	if m != nil {
		return m.OrderID
	}
	return 0
}

func (m *OrderDetailResp) GetItemID() uint64 {
	if m != nil {
		return m.ItemID
	}
	return 0
}

func (m *OrderDetailResp) GetAddressID() uint64 {
	if m != nil {
		return m.AddressID
	}
	return 0
}

func (m *OrderDetailResp) GetOrderStatus() OrderStatus {
	if m != nil {
		return m.OrderStatus
	}
	return OrderStatus_OrderStatusNone
}

func init() {
	proto.RegisterEnum("order.OrderStatus", OrderStatus_name, OrderStatus_value)
	proto.RegisterType((*CreateOrderReq)(nil), "order.CreateOrderReq")
	proto.RegisterType((*CreateOrderResp)(nil), "order.CreateOrderResp")
	proto.RegisterType((*OrderDetailReq)(nil), "order.OrderDetailReq")
	proto.RegisterType((*OrderDetailResp)(nil), "order.OrderDetailResp")
}

func init() { proto.RegisterFile("order/order.proto", fileDescriptor_fa47a2077d8980ed) }

var fileDescriptor_fa47a2077d8980ed = []byte{
	// 455 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0xbc, 0x53, 0x5d, 0x6f, 0xd3, 0x30,
	0x14, 0x6d, 0x58, 0xda, 0x6e, 0xb7, 0xac, 0xcd, 0xee, 0x60, 0x8a, 0x26, 0x24, 0xaa, 0x80, 0x44,
	0x85, 0xb4, 0x06, 0x0a, 0x2f, 0x15, 0x4f, 0xb0, 0x82, 0xd8, 0xcb, 0x56, 0x65, 0x3c, 0xf1, 0x32,
	0xb9, 0xf1, 0x55, 0x1b, 0xad, 0x89, 0x33, 0xdb, 0x99, 0xf6, 0xc2, 0xbf, 0xe0, 0xf7, 0xf1, 0x5b,
	0x50, 0xec, 0xf4, 0x23, 0x13, 0x7b, 0x43, 0x7b, 0x49, 0x7c, 0x7c, 0x8e, 0x7d, 0x8f, 0x7d, 0xae,
	0xe1, 0x40, 0x48, 0x4e, 0x32, 0x34, 0xdf, 0x61, 0x2e, 0x85, 0x16, 0xd8, 0x34, 0xe0, 0xf8, 0x30,
	0x16, 0x69, 0x2a, 0xb2, 0xd0, 0xfe, 0x2c, 0x17, 0xfc, 0x76, 0xa0, 0x7b, 0x2a, 0x89, 0x69, 0xba,
	0x28, 0x45, 0x11, 0xdd, 0xe0, 0x2b, 0x70, 0x17, 0xc4, 0xb8, 0xef, 0xf4, 0x9d, 0x41, 0x67, 0xd4,
	0x1b, 0x56, 0xfa, 0x88, 0x6e, 0xbe, 0x13, 0xe3, 0x91, 0x21, 0xf1, 0x0d, 0x34, 0xb5, 0xb8, 0xa6,
	0xcc, 0x7f, 0x62, 0x54, 0x07, 0x2b, 0xd5, 0xe7, 0x42, 0x2f, 0x7e, 0x94, 0x44, 0x64, 0x79, 0x3c,
	0x82, 0x56, 0xa2, 0x29, 0x3d, 0x9b, 0xf8, 0x3b, 0x7d, 0x67, 0xe0, 0x46, 0x15, 0xc2, 0x17, 0xb0,
	0xc7, 0x38, 0x97, 0xa4, 0xd4, 0xd9, 0xc4, 0x77, 0x0d, 0xb5, 0x99, 0x08, 0x24, 0xf4, 0x6a, 0xae,
	0x54, 0x8e, 0xaf, 0x6b, 0xb6, 0xbc, 0x8d, 0x2d, 0x95, 0x6f, 0xf9, 0x7a, 0x09, 0x3b, 0x24, 0x65,
	0xe5, 0x6a, 0x7f, 0x25, 0xfa, 0x2a, 0xa5, 0x90, 0x51, 0xc9, 0xa0, 0x0f, 0x6d, 0x73, 0x1d, 0x6b,
	0x43, 0x2b, 0x18, 0xdc, 0x41, 0xd7, 0x54, 0x9b, 0x90, 0x66, 0xc9, 0xf2, 0xff, 0xdf, 0xc4, 0xc3,
	0x95, 0xff, 0x38, 0xd0, 0xab, 0x95, 0x7e, 0x84, 0xe3, 0x6e, 0x05, 0xe3, 0x3e, 0x1c, 0x4c, 0xf3,
	0x5e, 0x30, 0xf8, 0x11, 0x3a, 0x66, 0x83, 0x4b, 0xcd, 0x74, 0xa1, 0xfc, 0x76, 0xdf, 0x19, 0x74,
	0x47, 0x38, 0xb4, 0xed, 0x76, 0xb1, 0x61, 0xa2, 0x6d, 0xd9, 0xdb, 0x1c, 0x3a, 0x5b, 0x1c, 0x1e,
	0x56, 0xc7, 0xb5, 0xf0, 0x5c, 0x64, 0xe4, 0x35, 0x70, 0x1f, 0xf6, 0x2e, 0x8b, 0x59, 0x9a, 0x68,
	0x4d, 0xdc, 0x03, 0xec, 0x40, 0xdb, 0x76, 0x00, 0xf7, 0x9e, 0xe1, 0x2e, 0xb8, 0x53, 0x96, 0x70,
	0x6f, 0x80, 0x4f, 0x61, 0x37, 0xa2, 0x98, 0x92, 0x5b, 0xe2, 0xde, 0xb4, 0x44, 0xa7, 0x2c, 0x8b,
	0x69, 0x49, 0xdc, 0x9b, 0x21, 0x40, 0xeb, 0x1b, 0x4b, 0xca, 0x71, 0x3c, 0xfa, 0x05, 0x4d, 0x53,
	0x02, 0xc7, 0xd0, 0xb2, 0xfb, 0xe0, 0xf3, 0xca, 0x65, 0xbd, 0xdd, 0x8f, 0x8f, 0xfe, 0x35, 0xad,
	0xf2, 0xa0, 0x51, 0x2e, 0xb5, 0x81, 0xac, 0x97, 0xd6, 0xfb, 0x63, 0xbd, 0xf4, 0x5e, 0x76, 0x41,
	0xe3, 0xcb, 0xf4, 0xe7, 0xf9, 0x3c, 0xd1, 0x8b, 0x62, 0x56, 0x46, 0x12, 0xde, 0xbe, 0x1f, 0x8f,
	0xdf, 0x85, 0xe6, 0xc1, 0xc5, 0x27, 0x73, 0xca, 0x4e, 0xe6, 0xe2, 0xba, 0x08, 0xe9, 0x8e, 0xa5,
	0xf9, 0x92, 0x54, 0x48, 0x6a, 0x21, 0x72, 0x4b, 0x87, 0xa2, 0xd0, 0x57, 0x73, 0x61, 0x9f, 0xef,
	0x27, 0x33, 0x75, 0x65, 0xc6, 0xb3, 0x96, 0x01, 0x1f, 0xfe, 0x06, 0x00, 0x00, 0xff, 0xff, 0x43,
	0x1a, 0x8b, 0x0e, 0xe0, 0x03, 0x00, 0x00,
}
